### ISSUE TITLE
Site only works with www

### ISSUE THREAD

**Issue by stojanvujkov** [laravel/valet#1054]
## Clear description of your problem
Installing Laravel Valet from scratch by following these instructions exactly, to a clean Mac M1 base model
https://laravel.com/docs/8.x/valet
It all works fine, except to the point where using "link" command, the website is only available via www subdomain, and not without it. "valet links" properly list the site with http://mysite.test and correct path of /Users/myname/code/mysite

Still www.mysite.test works, while mysite.test does not. 
How to get rid of www subdomain and have it available on http://mysite.test?
Please advise. Thank you.

## Expected behavior
Site to be available without www subdomain. In example http://mysite.test

## Current behavior
Site only works with www subdomain. In example http://www.mysite.test

## Steps to Reproduce
Installing Laravel Valet from scratch by following these instructions exactly, to a clean Mac M1 base model
https://laravel.com/docs/8.x/valet

**Comment by drbyte** [comment]
It seems that the `www.` requirement is being enforced by whatever application you have in the directory that the domain is linked to.

**Comment by stojanvujkov** [comment]
There is just a single index.php file with echo "Hello World" line in the linked directory, nothing else.

**Comment by drbyte** [comment]
Valet actually strips off the `www.` prefix if it's found in order to do its matching against your project directory name.

Is it possible that your browser has cached a redirect to a www version of that site? ie: is it happening with just one domain or absolutely every domain?

I'm using Valet on a dozen non-www non-subdomain sites daily. No forced www prefixes happening here.

**Comment by stojanvujkov** [comment]
It seems that it works fine with other folders/domains I create/link. Just this first one I have initially created requires www. 
I tried unlinking it, deleting its folder, linking again, tried Safari and Chrome, cleared browser cache, but the issue remains.
Any idea what could be producing or caching this? I dont see anything in Valet config.

**Comment by drbyte** [comment]
Maybe [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)?

You haven't said what exactly happens when you visit the URL without the www. subdomain. What error does the browser give you? Chrome sometimes gives more details than Safari does.

**Comment by stojanvujkov** [comment]
Visiting URL without www, in Safari it gives me "Safari Can't Open the Page" (this page is not responding), and Chrome gives me "This site can't be reached" took too long to respond (ERR_CONNECTION_TIMED_OUT). 
HSTS query in Chrome does not list this domain, I dont see it in Safari either.

**Comment by drbyte** [comment]
What's the output of `dig mysite.test` ? (where `mysite.test` is the domain in question, of course). In normal operation, any site served by Valet using dnsmasq to manage DNS, the `dig` output would show in the ANSWER SECTION `mysite.test  IN A 127.0.0.1` and under Query Time it would say SERVER: 127.0.0.1.

Perhaps you've got some override which points that domain someplace else? 
eg: did you manually add an override entry for that site to your `/etc/hosts` file, instead of letting Valet manage it with dnsmasq?

**Comment by stojanvujkov** [comment]
It turned out that I did have an entry in `/etc/hosts` pointing this domain (although without www) to an IP, left from my previous attempt to install Homestead on M1. Now that I have removed this entry, domain works properly through Valet, as expected, without www. 

Thank you!
