### ISSUE TITLE
Valet stop command doen't stop correctly

### ISSUE THREAD

**Issue by ElRochito** [laravel/valet#1063]
Hi,

When I run `valet stop`, dnsmasq and php services keep running.
I have to launch for each services `brew services stop <name>`

I use valet cli : 2.15

**Comment by drbyte** [comment]
This is by design.

`valet stop` intentionally only stops the current `nginx` and current `phpX@Y` instances.
It intentionally doesn't stop `dnsmasq` unless specified: `valet stop dnsmasq`, because forcing dnsmasq off could (depending on your configuration) break your dns and therefore all your internet access.

Further, note: the services upon which valet depends (dnsmasq, php, nginx) all run as root, so if you're going to manually start/stop things with `brew stop/start`, be sure to use `sudo`, ie: `sudo brew services stop <service>`, else you're not actually effecting relevant changes. And, you don't want to mistakenly start these dependent services as non-root else you'll have conflicting instances/permissions and unexpected behavior.

**Comment by ElRochito** [comment]
Ok thanks
