### ISSUE TITLE
Is it possible to group the System Certificate Trust Settings prompts?

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1081]
When running `valet install` on a server with a lot of SSL-encrypted sites (e.g. ones which I've used `valet secure` on), the System Certificate Trust Settings pop up shows up and requires me to type a password once for every secured site. It feels like we can maybe edit the trust settings once for all of the sites, instead of many times?

**Comment by mattcookdev** [comment]
This is the same behaviour on Mac's with fingerprint scanners as well. It will ask your fingerprint for every certificate. Would also love to see these grouped. Was quite surprised when I realised this was unaffected by `valet trust`.

<img width="511" src="https://user-images.githubusercontent.com/22277786/128200648-30ab9a67-845b-432d-b0fc-63d3614f8ef6.png">

**Comment by drbyte** [comment]
This only started since Big Sur (examples in #991). It doesn't occur on Mojave or older.

The feature to "trust" Valet's self-signed certificates was added in #515, released as v`2.1.0`

I think the System Certificate Trust Settings prompt is triggered in `Sites::unsecure()` by the call to `sudo security delete-certificate` which can only take one certificate at a time (`security` man page says: "The certificate to be deleted must be uniquely specified").
(To clarify, every call to `Sites::secure()` first calls `unsecure()` to clean out any old cert for the same domain. And `valet install` re-secures all sites found, to ensure their nginx stubs are updated. The `tld` command also re-secures all sites, so one would expect it to trigger the same prompts.)

**Comment by mattstauffer** [comment]
OK, so it looks like it's a system level change that we can only do one at a time. Oh well. Thanks for looking into it @drbyte!
