### ISSUE TITLE
`valet use`, when run in an isolated directory, should pull that directory's isolated PHP version

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1209]
https://twitter.com/JacobDelcroix/status/1503887481149796352

Currently `valet use` , when run in a directory with a `.valetphprc` file, pulls the PHP version from that file and uses it to change the global PHP Valet to that version.

It should also (this is a feature request, not a bug, but I'm the maintainer so I get that privilege of using issues this way bwahahahaha) read from the isolated PHP version.

**Comment by NasirNobin** [comment]
> https://twitter.com/JacobDelcroix/status/1503887481149796352

This tweet seems to be asking for CLI isolation, which is a must-have feature if we are using multiple versions on different projects. Otherwise `php artisan` or `composer` commands won't work. 

Personally, I've been using a hack that automatically swaps PHP Binary based on the directory I'm in. So `php artisan` & `composer` commands will always run on the project's PHP version.


<details>
 <summary>Here's a quick video demonstration </summary>
 
https://user-images.githubusercontent.com/13833460/158659897-f6376d8d-8dfa-4e2d-a82a-82bb0aafb009.mp4
</details>

Source code: [homebrew-instant-php-version-swap.zsh](https://gist.github.com/NasirNobin/3e5992608df21389dded1ac1661e1c7c)

I know the solution is very hacky and inefficient, but also kinda magical. I'll try to create a .zsh package or portable script that will read `.valetphprc` from the project root and will switch to that PHP version automatically. 

btw, @mattstauffer Do you think we can do something similar and just swap the PHP binary on the `$PATH` if the user runs `valet use` on an isolated directory?
