### ISSUE TITLE
valet change folder ownership

### ISSUE THREAD

**Issue by PATROMO** [laravel/valet#1220]
After fresh brew php installation:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/318564/160414248-a424f367-0484-4d87-93d7-18797e84e1b9.png">

After valet usage:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/318564/160414313-680a1b61-3554-4bd3-a1ba-1f2852d89eff.png">

This causes problems when upgrading the php version in the future. 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/318564/160414977-0dcc05ac-4b37-4e42-ae12-8f6f539fafaa.png">

**Comment by nicoverbruggen** [comment]
Hi, all! 

I wanted to chime in on this one, since I've [written about this](https://github.com/nicoverbruggen/phpmon/issues/85) as well when I was dealing with this issue in PHP Monitor and even shipped a feature/workaround that "fixes" this, called "[Fix Homebrew Permissions](https://github.com/nicoverbruggen/phpmon/issues/86)".

I don't think anything can be done about the ownership (it's a consequence of running `php` as `root`). However, reinstating the original permissions when you run `valet stop` might be a good idea. 

If implemented, you could then feasibly run `valet stop && brew upgrade php`, for example, without Homebrew then creating `.reinstall` folders, which would be awesome.

### Technical details

In phpmon, I restore the ownership like so...

`chown -R <username>:staff /path/to/directory` (default Homebrew permissions give the current user (accessible via `whoami`, and the `wheel` group access IIRC)

... for the following directories:

```swift
let directories = [
    "\(brewDir)/Cellar/\(formula)"
    "\(brewDir)/opt/\(formula)"
    "\(brewDir)/var/homebrew/linked/\(formula)"
];
```

So this has to happen for all installed PHP versions/formulae as well as for `nginx` and `dnsmasq`. I was going to take a look at this one myself and open a PR but I haven't had the time yet, unfortunately.

**Comment by driesvints** [comment]
@PATROMO What are the reasons for running php as root? (Thanks for chiming in @nicoverbruggen)

**Comment by nicoverbruggen** [comment]
I believe running all those services as `root` is required in order to successfully bind to port 80 on localhost, IIRC.

**Comment by PATROMO** [comment]
@nicoverbruggen thanks for explaining :) 
Yes, we need root to bind port 80. But I think that the folders should not change the ownership. :)

**Comment by nicoverbruggen** [comment]
That's a Homebrew thing, though. I don't think we are supposed to change those permissions as long as the services are running, or we risk breaking the services in question. 

I believe one of the reasons was that for the services to start at boot (which happens via a `plist` file), the executable must be owned by the user who will execute the process. If you were to change the ownership, Valet's services won't work correctly the next time you reboot your machine until you manually intervene.

I was also able to find [this explanation](https://github.com/Homebrew/discussions/discussions/234):

> Q: didn't we chown the files when running services as sudo?
> A: Yes, we do that because it's a security vulnerability to not do so. You'll need to sudo brew services stop (which fixes the permissions) before upgrading.

**Comment by driesvints** [comment]
Thanks @nicoverbruggen. Looks like we probably won't be intervening here if it's a Homebrew thing.
