### ISSUE TITLE
Invalid certificate for all parked and secured sites after updating Google Chrome

### ISSUE THREAD

**Issue by mdominguez** [laravel/valet#1300]
Hi,

After updating Google Chrome to the latest version (107.0.5304.87) we get an invalid certificate error for all of our parked and secured sites, so they won't load through HTTPS anymore. Still working fine on Safari.

This also occurred in Chrome Canary a couple of weeks ago (macOS 12 and 13), so we probably saw this coming 😅

Any ideas what could have triggered this situation in Google Chrome and if there's a way to fix?

If you need any more info that could be relevant to you, feel free to reach out!

Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LonnyX** [comment]
for those who are in the same case:

`valet uninstall`
`rm -rf ~/.config/valet`
`valet install`
`cd {your projects directory}` ⚠
`valet park`
`valet secure yourapp`

**Comment by w0rd-driven** [comment]
There are instructions to follow when using `valet uninstall`, to the point that I wouldn't recommend just blindly using that with the `--force` option.

`valet unsecure --all` had the effect of removing quite a few sites from `~/.config/valet/Nginx`, I use `valet link` instead of `valet park` because I don't want to serve the ~100 projects I have locally, just a handful. I had to manually prune keychain entries after running this because I have done quite a few uninstalls previously.

The problem as I understand it is the CA root certificates in `~/.config/valet/CA`. My guess is that the certificate chain expired and needed to be recreated and turns out this is correct according to the changes in https://github.com/laravel/valet/commit/1f15953c7330d6e88817e0677c16235794c7f089. The root chain is now set to expire in 20 years not 368 days as previously. I've removed all files in this folder and when I run `valet link` and then `valet secure` for the first time, the root cert files get created along with the certificate files for the particular project.

I now have to manually run `valet link`/`valet secure` again for each project I wish to keep but that's no different than `uninstall`. To be honest, the only use in my approach is that `~/.config/valet/Log` is kept intact but I manually pruned all the files in `CA`, `Certificates`, `Nginx`, and `Sites` because I wanted to do a deeper cleanse. In either case, I recommend running `valet links` and capturing the output in a file if you don't use `valet park` like me. It may be a good idea to capture this periodically if recreating 10+ sites is as time-consuming as it is for me.

Unfortunately, there wasn't a command to just recreate the CA root with the 20-year expiration and create new certificates. That was probably a good thing because it would've prompted me individually for the 14 sites I had secured. This won't be a problem again until 2042 so we will only need to secure the individual sites 396 days from when we run `secure`, or specify the `--expireIn=EXPIREIN` option to also have those expire on a date in the far future.

**Comment by brainmaniac** [comment]
> for those who are in the same case:
> 
> `valet uninstall` 
>`rm -rf ~/.config/valet`
>`valet install`
>`cd {your projects directory}` ⚠ 
>`valet park`
>`valet secure yourapp`

I needed to do this in addition to the list above:

`valet link` (from app root)
