### ISSUE TITLE
Update Ngrok integration

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1324]
I'm updating the Ngrok binary in Valet v4, and may move it to be managed by Brew; at @caseysoftware's suggestion I'll also just update the binary bundled with v3 in a minor release.

Also, I want to add an easy command to pass in your authentication token. It'll be something like
```
valet set-ngrok-token {token}
```

and it'll pass it through to 

```
ngrok config add-authtoken {token}
```

... update, our old version seems to instead use

```
ngrok authtoken {token}
```

To do:
- [x] Add `set-ngrok-token` command (#1325)
- [ ] Document `set-ngrok-token` command
- [x] Update binary (https://github.com/laravel/valet/pull/1318/commits/b5417e32d48562baa742a7ed6a7d55ef92a855ca)

**Comment by mattstauffer** [comment]
@caseysoftware We currently only have one ngrok binary that seems to somehow work for all Macs.

Will I have to differentiate which architecture they're on when I update? I went to download the latest binary and I see I have to pick the architecture (https://ngrok.com/download)

Thanks!

**Comment by caseysoftware** [comment]
We did some digging on our end. In the current setup, you have the x86_64 version of v2.3.40 and it generally appears to work, likely because of Rosetta 2:

```
> file .composer/vendor/laravel/valet/bin/ngrok          
.composer/vendor/laravel/valet/bin/ngrok: Mach-O 64-bit executable x86_64

> .composer/vendor/laravel/valet/bin/ngrok --version
ngrok version 2.3.40
```

So the immediate solution should be to embed the current version (3.1) of the x86_64 binary and it should continue to work.

Alternatively, you could add both arm & x86 of v3.1 and re-use this PR to let the uname make the call:
https://github.com/laravel/valet/pull/1182

**Comment by mattstauffer** [comment]
OK, fantastic! I'll look into these two options. Thanks @caseysoftware!

**Comment by mattstauffer** [comment]
In the end I actually moved ngrok to be installed via Brew. 😆
