### ISSUE TITLE
500 Internel Server Error Message

### ISSUE THREAD

**Issue by rsm23** [laravel/valet#143]
I've noticed that when I'm using laravel with valet, sometime I get a 500 Internal server error messages on all pages.
Everything works fine but "500 Internal Server Error" show up on all pages, sometimes in bottom of pages or sometimes on the top, **but when I restart Valet using** `Valet restart` the message disappears, maybe I'm not only one with this issue, or maybe this could help someone, or and I hope this issue will be fixed.

> I'm using MacOS Sierra _Version 10.12 Beta (16A313a)_ for the record

**Comment by adamwathan** [comment]
Hey! Valet currently doesn't officially support Sierra because the version
of Caddy we ship with doesn't support Sierra. Caddy 0.9.x does support
Sierra properly, but has a few bugs that break some unreleased Valet
features, so we haven't upgraded yet.

You can follow these instructions in the mean time to get it at least
working:

https://murze.be/2016/08/fixing-laravel-valet-macos-sierra/

The Caddy bug doesn't affect anything in a tagged Valet release, only
unreleased features on master so you are unlikely to run into any issues.
