### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by michaelw85** [laravel/valet#1505]
### Description

Current version `4.8.0` does not match latest release`4.8.1`.
This is quite frustrating when you upgrade php & valet but still get errors and think valet did not update.

https://github.com/laravel/valet/blob/master/cli/app.php#L36

### Steps To Reproduce

Install latest and run `valet -V` or `valet on-latest-version`

### Diagnosis

I can't submit a diagnosis it's too long even when removing deprecation errors...
I'm guessing this bug is pretty strait forward and a report is not needed.

**Comment by mattstauffer** [comment]
We'll tag `4.8.2` tomorrow. 

https://github.com/laravel/valet/commit/1a0077a69d412f132e65a3e93fb8184510a39dd1

**Comment by kozie** [comment]
To be fair, i've spent quite some time figuring out why my valet didn't seem to update, although it looked like it when i was updating packages (alongside valet+).
I had some troubles installing PHP 8.4 correctly.

Turns out, i figured out that the version number wasn't correctly updated and afterwards stumbled upon this GH issue.

2 weeks have passed by now and the `4.8.2` tag still hasn't been pushed. Just a minor heads up if you forgot to do so. Otherwise, please keep us updated :)

Thanks in advance and enjoy the holidays!

**Comment by michaelw85** [comment]
I also noticed it wasn't updated luckily I knew where to look this time helping out a coworker.

@mattstauffer  Can I help out to prevent this issue from occuring in the future?
