### ISSUE TITLE
Change port 80 to other port.

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/valet#163]
Hey,

would it be possible to make the port configurable, so that port 80 is not used?
I currently have a problem when running other services, since they use port 80 as well.

**Comment by adamwathan** [comment]
You could do this but you'd have to type the port as part of the URL which sort of sucks.

Should be able to it without us changing anything, just edit the port in ~/.valet/Caddyfile.

**Comment by lukasoppermann** [comment]
Ahh, okay, I feared it would be something like this, thanks in any case.

**Comment by lukasoppermann** [comment]
Sorry, somehow I can't get it to work.

I replaced

```
:80 {
    fastcgi / 127.0.0.1:9000 php {
        index server.php
    }
```

with

```
:8080 {
    fastcgi / 127.0.0.1:9000 php {
        index server.php
    }
```

And ran `valet restart`. Am I missing a step? demo.dev:8080 returns a 404.

**Comment by adamwathan** [comment]
Hey @lukasoppermann sorry I should've looked into this more before saying it was possible. 

There's basically no way you'll be able to use Valet nicely without being able to start certain services as root :/

Dnsmasq needs to run as root no matter what to be able to resolve .dev domains to localhost, even if you want to run the server on a different port.

We also start PHP FPM as root currently, but I'm not convinced this is totally necessary, so maybe something I can look into in the future.

We'd also need to make some small code changes to tell Valet to ignore the port portion of incoming requests when trying to match it to a project.

The main deal breaker though is Dnsmasq. The only real solution would be to add a hosts file entry for every project just like you might do with a virtual machine, which would really make the experience a lot worse. You also might not have access to your hosts file since it's owned by root :/

**Comment by lukasoppermann** [comment]
I see how it is a dealbreaker for you and valet, as it would negate the beautiful simplicity, but could I do it my just setting it in the hosts file?

**Comment by adamwathan** [comment]
We would still need to make code changes to Valet to make it possible at the moment, so not currently unfortunately.

**Comment by lukasoppermann** [comment]
Ahh, okay, thanks for your help anyway.

**Comment by demetre19** [comment]
Has this issue been resolved? Is there a way to share on mac?

**Comment by drbyte** [comment]
Valet 2 expects to use ports 80 and 443, since it's intending to provide standard webserver services.
It also internally uses port 60 when operating with ngrok to share via a URL that can be accessed external to your Mac.

But all of its nginx configs can be individually manually overridden if you want to serve a specific site on a different port. These configs are somewhat volatile though, since some valet CLI commands will need to rebuild (rewrite) the nginx configs.

**Comment by safal123** [comment]
> Hello
