### ISSUE TITLE
Can valet support other PHP source?

### ISSUE THREAD

**Issue by ChiVincent** [laravel/valet#178]
Hello, 

I want to use [phpbrew](https://github.com/phpbrew/phpbrew) when using valet, but valet install php from [homebrew](http://brew.sh/) automatically. 

Could I choose my own php when using valet?

**Comment by adamwathan** [comment]
Currently not because some of Valet's configuration and installation steps depend on where Homebrew is putting certain PHP files. It would be nice to not have to do that, but I'm not sure we want to take on the maintenance burden of making sure Valet works properly with an unknown number methods for installing and configuring PHP.

**Comment by KorvinSzanto** [comment]
This actually works for me today using the following flow:
If using PHP7:
```sh
$ brew unlink php70
$ brew link php56
$ valet install
$ valet restart
```
and to get back:
```sh
$ brew unlink php56
$ brew link php70
$ valet install
$ valet restart
```

and that works great. I probably don't need the call to install as long as it's already been installed once before but I throw it in there for good measure.

**Comment by adamwathan** [comment]
@KorvinSzanto You are using Homebrew for PHP 5.6 though, @ChiVincent wants to use a PHP installation that does not come from Homebrew. Your workflow is definitely one we intend to continue to support 👍

**Comment by zhwei** [comment]
I wrote a simple valet plugin, may be help you.  https://github.com/zhwei/valet-phpbrew-ext
