### ISSUE TITLE
[ERROR 502 /server.php] dial tcp 127.0.0.1:9000: getsockopt: connection refused

### ISSUE THREAD

**Issue by gaillafr** [laravel/valet#240]
After having upgraded I can see in the logs (manually) the VHost is trying to communicate via TCP port 9000 but the www.conf specifies a socket in my home directory: /Users/myname/.valet/valet.sok

**Comment by triasrahman** [comment]
Same issue. Any solution?

**Comment by Pro777** [comment]
I'm getting this same issue after install valet a number of time. I even built php71 from the source.

**Comment by mattstauffer** [comment]
@gaillafr @triasrahman @Pro777 Any of y'all still having this issue?

**Comment by triasrahman** [comment]
@mattstauffer nope, it works after I downgrade to php70, never try php71 again.

**Comment by drbyte** [comment]
I'm pretty sure this would have been a result of using older *.conf files for sites configured using an older version of Valet, since it was older versions that used the port 9000. In v2 it was switched to `valet.sock`. Uninstalling and reinstalling Valet (and the affected homebrew PHP version) typically has resolved such symptoms.

**Comment by mattstauffer** [comment]
Great--thanks both!
