### ISSUE TITLE
Issue running PHPStan

### ISSUE THREAD

**Issue by james2doyle** [laravel/valet#292]
I just installed [phpstan](https://github.com/phpstan/phpstan) 5.2 (installed globally) and I got the following warning when running any commands:

```
PHP Fatal error:  Cannot redeclare info() (previously declared in /Users/james/Sites/project-test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:454) in /Users/james/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 22
PHP Stack trace:
PHP   1. {main}() /Users/james/.composer/vendor/phpstan/phpstan/bin/phpstan:0
PHP   2. require_once() /Users/james/.composer/vendor/phpstan/phpstan/bin/phpstan:19
PHP   3. ComposerAutoloaderInit85b5b5c41571d8fc5d92d71a726ab61a::getLoader() /Users/james/.composer/vendor/autoload.php:7
PHP   4. composerRequire85b5b5c41571d8fc5d92d71a726ab61a() /Users/james/.composer/vendor/composer/autoload_real.php:56

Fatal error: Cannot redeclare info() (previously declared in /Users/james/Sites/project-test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:454) in /Users/james/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 22
```

Valet line in question: https://github.com/laravel/valet/blob/v2.0.3/cli/includes/helpers.php#L19-L22

The same error occurs in the actual framework itself as well...

Seems like it doesn't like the fact that info is declared twice.

And thoughts?

**Comment by adamwathan** [comment]
It's unfortunately pretty common for global composer dependencies to collide, since they are all resolved against a single composer.json file and are all autoloaded together, even when you are just installing independent tools that should have their own isolated environment.

I recommend using this to install global dependencies instead: https://github.com/consolidation/cgr

We could namespace all of that stuff but it's sort of a band aid solution to a bigger issue.

**Comment by james2doyle** [comment]
I understand.

But why not wrap the valet helpers in `! function_exists` checks? It seems like this is partially in place already. For example [this function here](https://github.com/laravel/valet/blob/v2.0.3/cli/includes/helpers.php#L50).

**Comment by adamwathan** [comment]
The problem with that approach is that the rest of Valet expects `info` to do one thing, but if it was already defined by `phpstan`, it will do something completely different.

Our `info` function is meant to write console output with a certain format, so if Valet is calling the `phpstan` version of `info` instead, it won't write the console output and will instead do something different.

The existing functions that are wrapped with `function_exists` are only wrapped because the Laravel installer provides those same functions with the same implementation, but really the problem is still there.

We should just namespace by default, and encourage using `cgr` either way, hopefully soon.

**Comment by james2doyle** [comment]
> The problem with that approach is that the rest of Valet expects info to do one thing, but if it was already defined by phpstan, it will do something completely different.

Maybe I wasn't clear, but it is actually complaining about the project (Laravel) and Valet having 2 `info` functions, which are the same code BTW.

See this line in isolation:

```
Cannot redeclare info() (previously declared in /Users/james/Sites/project-test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:454) in /Users/james/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 22
```

Does that clarify? It is complaining about Valet and my local Laravel project. PHPStan doesn't have an `info` function, it just bubbled this error to the surface.

**Comment by adamwathan** [comment]
Oh weird that is mega bizarre, I have no idea why that is happening.

This is happening when running phpstan against your project? It sounds like phpstan is autoloading your project which is then colliding with stuff autoloaded by global composer :/

**Comment by james2doyle** [comment]
Yeah I know right? This seems to be happening with Laravel projects in particular. I [made an issue on PHPStan](https://github.com/phpstan/phpstan/issues/84) and the answer was basically "there are conflicting functions with the same name, PHPStan alerted you of them".

To recreate, just go to the root of a Laravel project (the one I was testing was a 5.2) and do a `phpstan analyse --autoload-file=vendor/autoload.php app/` and bam - fatal error.

I will check the `cgr` tool as well.

It's strange because I don't get this with global `phpunit` or anything else...

**Comment by adamwathan** [comment]
Yeah I think it's just because PHPStan is autoloading it's own autoloader *and* the projects autoloader into the same process. They are right about the conflict, again best way to solve is for PHPStan be installed in it's own isolated environment, so it doesn't carry Valet with it when you run it.

You could install PHPStan to it's own folder manually and add that folder to your path if you wanted as well. The root cause is just that PHPStan and Valet share a vendor directory because of how global Composer dependencies (unfortunately) work.

**Comment by james2doyle** [comment]
Yeah, I see. It does mention running it via `vendor/bin/phpstan` vs globally. But globally is still an option.

Additionally, it is very weird because the conflict _is not_ between Valet and PHPStan. It is between the app being tested (local Laravel) and global Valet....

**Comment by adamwathan** [comment]
Yeah again this is because when you run PHPStan, it autoloads everything in ~/.composer/vendor, which includes *every* globally installed tool.

So running PHPStan could be loading PHPUnit's dependencies, Valet's dependencies, the Laravel Installer's dependencies, etc. because Composer dumps them all in one bucket.

So when PHPStan loads up your project, it already has Valet loaded thanks to Composer forcing PHPStan and Valet to share a vendor folder, so it causes a collision.

**Comment by james2doyle** [comment]
Ew. Well, I'm sure someone else with experience this at some point and will be led here by Google.

**Comment by loeffel-io** [comment]
I got the ~same problem

```
Fatal error: Cannot redeclare double_to_euro() (previously declared in .../app/Helpers.php:40) in .../app/Helpers.php on line 47
```

`function_exists` solved the issue 👍
