### ISSUE TITLE
Use different TLD

### ISSUE THREAD

**Issue by MikeNGarrett** [laravel/valet#294]
Since [Google registered](https://www.iana.org/domains/root/db/dev.html) the TLD `.dev`, it may be a good idea to change the default to [one of the reserved TLDs](https://tools.ietf.org/html/rfc2606): `.localhost`, `.test`, or `.example`.

**Comment by drbyte** [comment]
I much prefer `.dev` because it's short and expressive. I've no interest in typing `.localhost` every time I'm working on a local dev site. Doesn't feel very `zonda` 🤕 

Granted, one can change the default to whatever they like, using `valet domain` ... so I could change it back to `.dev` if I had to. But I hope it doesn't get changed. 

Fortunately valet also configures `dnsmasq` to intercept calls to `.dev` so they're served locally. Only downside there is if one actually needed to use some official .dev domain. If that were to become a daily clash then I'd reconsider my current workflow. For now I prefer `.dev`.

Of course, others may have a different opinion.

**Comment by adamwathan** [comment]
We're gonna keep .dev as the default until it actually becomes a problem. Right now I don't think there's actually a single publicly accessible .dev website so hasn't been an issue.

As @drbyte mentioned, of course it's easy to switch this to something else for yourself locally, and should it ever actually cause any real problems, we'll figure out something else 👍

**Comment by benlk** [comment]
Right now, running `dig` for any `.dev` domain will return an IP address of `127.0.53.53`: https://www.icann.org/resources/pages/name-collision-2013-12-06-en

vvv has been having this problem as well: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583

Using Valet with a `.dev` domain occasionally results in `ERR_ICANN_NAME_COLLISION` errors in Chrome, sometimes.

**Comment by drbyte** [comment]
It's an easy fix to your own configs.

See #115 and https://github.com/laravel/valet/issues/299#issuecomment-274177318 for custom dnsmasq configuration that will avoid the ICANN_NAME_COLLISION issue.

**Comment by Sacro** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/669923

Time to reopen?

**Comment by benlk** [comment]
Main discussion seems to be happening in https://github.com/laravel/valet/pull/436

**Comment by MikeNGarrett** [comment]
Glad to see the switch is happening to `.test`!
