### ISSUE TITLE
ability to import/export to file for migrating/sharing valet configurations?

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#366]
I've got over 50 valet links and would like to migrate to another mac that's going to have an identical folder structure. It would be very handy to be able export everything to a file.. json or yaml or whatever and be able to import it back elsewhere

could this be implemented? or is there a solution for this?

**Comment by adamwathan** [comment]
The way `links` works is by creating a symlink from your project into `~/.valet/Sites`, so you could write a little script to run over each of those symlinks and output them to a file if needed.

**Comment by vesper8** [comment]
ah thank you, that's helpful

but what about the 'secure' flag? I've run valet secure on nearly every one of them, do I have to make a script to re-run the valet secure again or is there a way to restore that more easily? what does valet secure do exactly?

**Comment by adamwathan** [comment]
No you'd have to re-run it because it needs to generate new SSL certs for each site and trust them in your Mac's keychain. It's definitely possible to add a feature to Valet that keeps track of your links in a config file and lets you restore it on a new machine but I don't personally have the time to spend on that any time soon.

**Comment by adamwathan** [comment]
Closing this for now as there's no concrete plans to implement a feature to handle this.
