### ISSUE TITLE
how can I disable autostart daemon?

### ISSUE THREAD

**Issue by rafaeldevsquad** [laravel/valet#374]

**Comment by adamwathan** [comment]
Running `valet stop` will stop the services Valet uses and those shouldn't restart automatically after reboot or anything. Can you explain what you've tried and what you are seeing that's undesirable?

**Comment by marcwieland95** [comment]
In my case, Valet is always starting on boot on my Mac.
When I call `valet stop` sometimes the `dnsmasq` service is still running. I don't know if this is an issue of Valet or I have something else keeping it running.

If somebody else has this issue: I'm stopping the service manually via brew. It's a bit annoying since I need to do it on every restart. -> `sudo brew services stop dnsmasq`

**Comment by drbyte** [comment]
Why do you want it always off?
Perhaps simply tweaking its config would suffice?

**Comment by marcwieland95** [comment]
In my day-to-day work, I use something different which uses dnsmasq as well.

I guess within Valet I can't change the configuration and disabling the autostart seems not possible as well

**Comment by drbyte** [comment]
@marcwieland95 wrote:
> In my day-to-day work, I use something different which uses dnsmasq as well.
> 
> I guess within Valet I can't change the configuration and disabling the autostart seems not possible as well

If you want to use Valet's dnsmasq config, you can copy/move your other dnsmasq settings into the settings file that Valet uses:
`/Users/YOU/.config/valet/dnsmasq.d/*.conf`

For example, I like to use OpenDNS instead of whatever my router is picking, so I configure Valet's dnsmasq to use that this way:

- create new file named: `/Users/YOU/.config/valet/dnsmasq.d/dns-opendns-normal.conf`
- inside that `dns-opendns-normal.conf` is the following:
```conf
# fallback servers to use if we can't resolve using our own rules
# these are for open-dns
server=208.67.220.222
server=208.67.220.220
```

Or to turn off the DNS caching you could put the following in a file named `/Users/YOU/.config/valet/dnsmasq.d/cache-off.conf`:
```conf
# default is 150, or 0 = off
cache-size=0
```

etc
