### ISSUE TITLE
Question / Proposal: Nginx configuration

### ISSUE THREAD

**Issue by arjasco** [laravel/valet#400]
Hello!

This is not an issue so sorry if you have a place for chat like this. I have a question and possible proposal for future development.

Is there any way to be able to modify the nginx configuration files for each site? I understand this is suppose to be an out of the box solution that doesn't mean digging around with configuration. But the ease of having everything running on my host machine is why I prefer Valet over a VM. 

Could it be possible to maybe have a .valet file in your project root which you can define includes / extra configuration to the nginx conf. Possibly other general valet options also eg defining additional subdomains for your project. I understand that you would probably have to run a provision command of some kind to then apply what is in the .valet file.

This would be useful as it give you a little extra control over the server and can be added to version control for the rest of the team to adopt the same configuration also.

**Comment by adamwathan** [comment]
With Valet, all site configuration is actually written in PHP, we use a single Nginx configuration that points to a single PHP entry point, and then that delegates to your project using the correct server configuration rules based on the project type detected.

For example, here is how Wordpress is served with Valet:

https://github.com/laravel/valet/blob/master/cli/drivers/WordPressValetDriver.php

If you would like to customize how your site is served using Valet, you should write a custom driver for your project and bundle it right into your project. Instructions for that are here:

https://laravel.com/docs/5.4/valet#local-drivers

We'll never expose nginx configuration because there's no guarantee we stay on nginx forever; that's just an implementation detail with Valet. We used to use Caddy instead of nginx for example, and might switch back eventually.
