### ISSUE TITLE
Chrome to force https on .dev

### ISSUE THREAD

**Issue by lesaff** [laravel/valet#434]
This might change the way Valet sets https/secure settings?

Per this article
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

and this commit
https://chromium-review.googlesource.com/c/chromium/src/+/669923

**Comment by adamwathan** [comment]
Yep we'll change the default TLD I guess as annoying as that is.

**Comment by joshmanders** [comment]
Wouldn't it be better to do `secure` by default on domains?

**Comment by adamwathan** [comment]
Nah I think better to use a TLD reserved for local development so we're just not at the mercy of this stuff. I personally don't secure any of my local stuff, and it's impossible to do it by default because of the dynamic nature of how parked project folders work.

**Comment by joshmanders** [comment]
Ah yeah, I keep forgetting about parked folders.

**Comment by rap2hpoutre** [comment]
[People](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/) are talking about `.localhost`, what do you think about it?

**Comment by clarkeash** [comment]
`.test` is also an option https://en.wikipedia.org/wiki/.test

**Comment by freddinator** [comment]
#436 is addressing this

**Comment by andyunleashed** [comment]
@clarkeash I agree with .test - as it's a reserved name so in theory should never been over-ridden.

**Comment by clarkeash** [comment]
@andyunleashed I think they are going to go with .localhost (which is also reserved) but will be easy to change on your machine to whatever you want.

**Comment by andyunleashed** [comment]
@clarkeash Are you able to set the TLD when using `valet park`?

**Comment by drbyte** [comment]
Changing the TLD to .test can be done by typing:

valet domain test

**Comment by joshmanders** [comment]
`valet domain bananasandwich`

**Comment by andyunleashed** [comment]
Great, thanks both. Also @joshmanders - `.bananasandwich` is most definitely going to be my development TLD moving forward.

**Comment by drbyte** [comment]
For quick reference, here's a perpetual list of "claimed" TLDs: https://data.iana.org/TLD/tlds-alpha-by-domain.txt ... ie: the ones to *not* use.

**Comment by svenluijten** [comment]
In addition to @drbyte's comment, [here](https://tools.ietf.org/html/rfc6761) is the RFC that specifies and encourages the use of `.test`, `.example`, `.invalid`, and `.localhost`. (and [here](https://iyware.com/dont-use-dev-for-development/) is an easier to parse blogpost)

Personally I'd use `.localhost`, as it'd be immediately recognizable as being hosted on the local machine instead of on a seperate server with some DNS trickery.

**Comment by rjchauhan** [comment]
`.devv` is also working!

**Comment by joshmanders** [comment]
All I read is `.dew` and now all my apps are named `mountain.dew`

**Comment by rockbarato** [comment]
`.vanilla` is an option too.

**Comment by maschultz** [comment]
![screenshot 2018-09-29 02 04 52](https://user-images.githubusercontent.com/35410468/46241738-1d58d980-c38c-11e8-8d23-e43e6eb578a1.png)

`valet domain dev`

then check chrome for an inevitable error, which is now apparently now normal due to SSL shitz (09.29.18), then try:

`valet secure`

Chrome 69.0.3497.100 (Official Build) (64-bit) then works for me in macOS Mojave.

-- MS//

**Comment by joshmanders** [comment]
Yes you can still use `.dev` by securing your site, but now that they released https://v8.dev they've basically went back on their "We're only using `.dev` internally` and they'll most likely put something else on that TLD too, so you're gonna have problems soon. Best to switch to `.test`
