### ISSUE TITLE
[DomainException]  Unable to determine linked PHP. 

### ISSUE THREAD

**Issue by tom9527** [laravel/valet#470]
already add **echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc**   **source ~/.bashrc** still got this error

**Comment by drbyte** [comment]
According to the Valet code where the `Unable to determine linked PHP` message is generated, it could appear for two reasons:

1. At https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L179 it's checking whether a symlink exists for any php binary.
If it's this line that's triggering it, then the fix is to run `brew link php71` (or whatever PHP version you've installed with homebrew).

2. At https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L187 it's been checking whether the symlink is pointing to a version of PHP that Valet supports (currently 5.6, 7.0, 7.1, 7.2).
In this case, you may need to "unlink" yourself from unsupported PHP versions, and then re-link to a supported version.

`brew unlink php55`
`brew link php71`

**Comment by tom9527** [comment]
have installed php71, after brew link php71, got this error--  **/usr/local/sbin is not writable.**  I googled and people recommend   **sudo chown -R 'whoami':admin /usr/local/sbin** , but got this **No such file or directory**

**Comment by tom9527** [comment]
I checked my /usr/local/, get my bin file but no sbin file

**Comment by tom9527** [comment]
Finally get it done, under local/ , by mkdir sbin and brew link php71. **Valet installed successfully!**

**Comment by matrunchyk** [comment]
The problem is because `linkedPhp` method can't match a linked PHP version. In my system the path is `../Cellar/php/7.2.2_13/bin/php`.
In order to fix that, I've added a new entry to `supportedPhpVersions` function of `~/.composer/vendor/laravel/valet/cli/Valet/Brew.php` file:

```
function supportedPhpVersions()
{
    return collect(['7.2', 'php72', 'php71', 'php70', 'php56']);
}
```

@adamwathan can we add `7.2` to the array to catch cases like this one?

**Comment by drbyte** [comment]
If you're using `dev-master` or v`2.0.8` or newer, then `php` is already in the list, so `7.2` is superfluous:

https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L55

**Comment by matrunchyk** [comment]
Ahh yeah, forgot to update, my bad. V `2.0.8` resolves the issue.

**Comment by kevmt** [comment]
got it fixed using using 7.1:

```shell
$ brew install php
$ brew install php7.1
# for @179
$ ln -s /usr/local/Cellar/php@7.1/7.1.16 /usr/local/Cellar/php/7.1.16
# for @187
$ ln -s /usr/local/Cellar/php/7.1.16/bin/php /usr/local/bin/php
$ valet install
```

**Comment by robertkent** [comment]
@kevmt this worked for me thanks! Be careful with the new PHP@7.1 as it includes some extensions in the binary so you may have to remove some old versions of ext-mcrypt.ini etc

**Comment by kevmt** [comment]
@robertkent gotcha

**Comment by bravist** [comment]
i use it 

```bash

ln -s /usr/local/Cellar/php71/7.1.16_1/bin /usr/local/bin/php


```

**Comment by chrisbjr** [comment]
Issues posted above could be linked to #562 

There is a fix there that worked for me:

`brew link --force --ovewrrite php@7.1`

**Comment by kevmt** [comment]
For newly installed OS, this is my GIST: https://gist.github.com/kevmt/1260e58fc94c8194c24d8468fb079da6

**Comment by naveen3273** [comment]
I think it's caused by this commit to valet: https://github.com/laravel/valet/commit/84ade711b61fd79ead98e08b5186704f68b4f993

Looks like the change to collections causes the index to be compared instead of the the actual version.

Edit: This happens if you are running a version of Laravel < 5.3. To fix, run: composer global update

Reference from 
https://laracasts.com/discuss/channels/laravel/laravel-valet-domainexception-unable-to-determine-linked-php

**Comment by jonathanstegall** [comment]
The comment above, https://github.com/laravel/valet/issues/470#issuecomment-383824154, solves this issue for me.

**Comment by jolamar** [comment]
`composer global update`

**Comment by AK-PapaSoft** [comment]
My way to fix this was ti rewrite current php version: `brew link php@7.1 --force --overwrite`
That worked for me in similar case. If you have questions in the whole process - ping me as well. Probably, I can help ;)

**Comment by AlemAblat** [comment]
1. export PATH="$PATH:$HOME/.composer/vendor/bin"'
2. ln -s /usr/local/Cellar/php@XXXX /usr/local/bin/php
3. valet install
Enjoy!

**Comment by 6thCode** [comment]
After creating this PATH:-
ln -s /usr/local/Cellar/php71/7.1.16_1/bin /usr/local/bin/php

Do this:-
➜ `composer global require laravel/valet`
➜  `valet install`

Hope it works for you!!

**Comment by EarlBromStyle** [comment]
> After creating this PATH via your terminal:-
> `ln -s /usr/local/Cellar/php71/7.1.16_1/bin /usr/local/bin/php`
> 
> Do this:-
> ➜ `composer global require laravel/valet`
> ➜ `valet install`

This is the solution even if it destroys the easy way to switch php versions.
Watch out that you symlink the right path!

In my case (linking to 7.2) the symlink looked like
ln -s /usr/local/Cellar/valet-php@7.2/7.2.13/bin/php /usr/local/bin/php
