### ISSUE TITLE
Problem installing --with-mariadb (Filesystem.php line 266)

### ISSUE THREAD

**Issue by jasontucker** [laravel/valet#485]
$ valet install --with-mariadb
[nginx] Stopping
[php70] Stopping
[php71] Stopping
[mariadb] Stopping
[redis] Stopping
[devtools] Installing
[devtools] wp-cli already installed
[devtools] n98-magerun already installed
[devtools] n98-magerun2 already installed
[devtools] pv already installed
[php70] Installing extensions
[php70] apcu already installed
[php70] intl already installed
[php70] mcrypt already installed
[php70] opcache already installed
[php70] geoip already installed
[php70] Restarting
[dnsmasq] Restarting
[mariadb] Stopping
[mariadb] Configuring

In Filesystem.php line 266:

  RecursiveDirectoryIterator::__construct(/usr/local/var/mysql): failed to open dir: No such file or directory

install [--with-mariadb]

**Comment by mattstauffer** [comment]
I'm not one of the authors of Valet, I'm just helping clean up the issues and PRs a bit, so I'm sure I'm just dumb, but I wasn't even aware of this flag and I don't see it in the codebase, so I assume you're doing one of two things:

1. Taking advantage of a feature I'm not aware of where you pass flags to `valet install` that are intended to be passed along to its dependencies

or

2. Using Valet a way it's not intended to be used. 

Because I don't know which it is, could you explain a bit more about what you're expecting here so I can see if I can help?

Thanks!

**Comment by adamwathan** [comment]
Closing, Valet doesn't have this feature, you must be using https://github.com/weprovide/valet-plus.
