### ISSUE TITLE
2.0.10 - valet restart, no longer restarts PHP fpm process

### ISSUE THREAD

**Issue by epreston** [laravel/valet#558]
This release no longer finds and restarts php when running `valet restart`

I had this all working in #549 now its not.

**Comment by RobvH** [comment]
```sh
╭─rob.vanhoose@endor: brstack/RobvH/valet  master
╰─▶ ps -ax | grep php-fpm
35289 ??         0:00.07 /usr/local/opt/php/sbin/php-fpm --nodaemonize
35310 ??         0:00.00 /usr/local/opt/php/sbin/php-fpm --nodaemonize
35311 ??         0:00.00 /usr/local/opt/php/sbin/php-fpm --nodaemonize
╭─rob.vanhoose@endor: brstack/RobvH/valet  master
╰─▶ valet restart        
Restarting php...
Restarting nginx...
Valet services have been restarted.
╭─rob.vanhoose@endor: brstack/RobvH/valet  master 
╰─▶ ps -ax | grep php-fpm
36589 ??         0:00.06 /usr/local/opt/php/sbin/php-fpm --nodaemonize
36596 ??         0:00.00 /usr/local/opt/php/sbin/php-fpm --nodaemonize
36597 ??         0:00.00 /usr/local/opt/php/sbin/php-fpm --nodaemonize
```

Restarted perfectly. Can you provide more information about your environment or any errors you're getting?

**Comment by epreston** [comment]
It restarted perfectly only because your php is called “php”.  Link php@7.1 or php@7.2.  You’ll notice the “restarting php” message go away. Also any function like isphpinstalled will return false.

**Comment by epreston** [comment]
I don't mind how we get a solve on this.  Use the regular expression fix in all places where the array is referenced and my test environments will work.  That would be a modification to `hasInstalledPhp` as well introduce a regular expression that works in all cases.

The history on this seems to be both of us quickly putting up patches to get back to work.  Due to the time differences, nobody seeing what everyone is doing.  I haven't helped the situation with my lack of confidence introducing changes to the unit tests.  It also looks like Taylor and Adam didn't have much comms in the state it was left between releases and versions.

How can i help to have this sorted over the weekend?

**Comment by RobvH** [comment]
If you want to use php@7.1 you would normally unlink 7.2 and force link the cask, no? Is there a better way? I always need php and php-fpm to be called by their proper names for my scripts, ides, etc to work. 

Indeed, I was working with a colleague trying to get him set up and came across the syntax issue in the current version and found it reverted in dev but still not working. Hence, I offered the fix. 

I think there are a few things we need to sort out with the changes in the linking. This new strategy for distributing PHP has the advantage of pushing people to the latest version, but also significantly at inhibits using older versions. This is by design. 

 I’m willing to help anyway I can.

**Comment by epreston** [comment]
Thank you my man, I need to step back from this one.
