### ISSUE TITLE
[Linux] Officially Support and work on Valet Linux or something like that

### ISSUE THREAD

**Issue by IamManchanda** [laravel/valet#568]
https://github.com/cpriego/valet-linux

cc @cpriego

**Comment by IamManchanda** [comment]
Just like Mac, 
It's Unix-like after all so what's the issue??

{ I understand windows official support not that possible }

**Comment by IamManchanda** [comment]
And I totally don't understand why Laravel Team wanting Linux users to install a Virtualized **Linux** Environment (HomeStead) for their local development instead of Easier things like *Laravel Valet*

**Comment by adamwathan** [comment]
We won't ever build an official Linux version of Valet because neither me or Taylor use Linux for development, so we aren't willing to commit to supporting it and dealing with bugs and fixes for free when we won't even be using it. Valet is very much an "open source because why keep it closed source" project; we built it for ourselves but anyone else with the same needs is free to use it too.
