### ISSUE TITLE
Help to create a Custom Valet Drivers

### ISSUE THREAD

**Issue by florianbouvot** [laravel/valet#578]
Hi, on some project I use a custom CMS developped by a coworker.

Everything works well with Valet except images resized or cropped by the CMS :

* htaccess :
```
RewriteCond %{REQUEST_URI} !App/assets
RewriteCond %{REQUEST_URI} !AppEdit/assets
RewriteCond %{REQUEST_URI} !AppTweeb/assets
RewriteRule \.(?:jpe?g|JPE?G|gif|png)$ AdaptiveImages.php
```

* twig template example :
```
<img {{ image(entry.picture_url, 'crop-resize-name') }}>
```

* crop/resize settings example : 
```
"crop-resize-name" => array(
   "width" => 300,
   "height" => 200
),
```

* URL
```
/crop-resize-name/path-to-image/image-name.jpg
```

Can anyone help me create the custom driver for this htaccess rewrite rules ?

**Comment by florianbouvot** [comment]
Anyone on this?

**Comment by alexfinnarn** [comment]
@florianbouvot Valet uses NGINX instead of Apache so I would try https://www.nginx.com/blog/creating-nginx-rewrite-rules/ and add your .conf file to https://github.com/laravel/valet/blob/master/cli/stubs/nginx.conf#L39

As far as the driver file goes, I use Drupal and https://github.com/laravel/valet/blob/master/cli/drivers/DrupalValetDriver.php#L52 can be worked with potentially to redirect the request, maybe. But I think the NGINX redirect is cleaner.

**Comment by drbyte** [comment]
@florianbouvot does this still need assistance? If not, please click Close.

If it does, can you please provide additional code information to explain what's happening?
