### ISSUE TITLE
Issue when running with multiple mac users

### ISSUE THREAD

**Issue by ollieread** [laravel/valet#598]
Running valet using multiple users causes a particular issue.

When attempting to access any projects on the other user account, I received this:

    Did not get front controller from driver. Please return a front controller to be executed.

After some digging, I discovered that the installation was using the configuration stored for the primary user.

To resolve this, you need to open the terminal as the primary user, change to the other users directory;

    cd /Users/otheruser/whatever/directory/path/sites/are/in

And then run;

    valet park

I appreciate that this might be a rare case, but the documentation does not make this entirely obvious. Although valet lets me initialise it as the secondary user, and run the commands, they store the results in a directory that is never used.

I'm unsure whether this is just a gap in the documentation or an issue with how it stores the config. It could even be a limitation of composer, or OSX.

**Comment by drbyte** [comment]
@ollieread This is really an issue of trying to run a shared server application (nginx) which is configured to serve files from a single identified source.  Basically valet is primarily designed to implement its configuration in a way that uses only a single set of files. 

Your workaround essentially tells valet to continue using its single set of configuration files, and merely adds another listing of directories to identify for finding files that could be served using that configuration.
I wouldn't be surprised if it also ran into some file-permisison/ownership issues as well. 

It's a limitation driven by running the non-Server version of OSX/MacOS, and since the vast majority of users are indeed using the non-Server install of OSX and also largely with just a single user per machine, valet's design suits that top 90+% of the population.
This primarily-for-single-user-macs design could be changed to more aggressively support multi-user-macs, but doing so will also make installation more complicated and introduce security-level changes, leading to increased package complexity, and increased support challenges. It won't surprise me if it isn't changed (much).

**Comment by charpun** [comment]
Running the following to change the ownership of Homebrew directories to the current user as well as update Valet and Nginx config files to point the current user has been working for us. This may not work with every situation, but might provide another potential solution. 

```
#!/usr/bin/env bash
 
USER=$(whoami)

sudo chown -R $USER $(brew --prefix)/*
STR='Users\/[a-zA-Z0-9]*\/'
REPLACE="Users\/$USER\/"
REGEX="s/$STR/$REPLACE/g"

sed -i '' -e $REGEX /usr/local/etc/nginx/valet/valet.conf
sed -i '' -e $REGEX /usr/local/etc/nginx/nginx.conf
sed -i '' -e $REGEX /usr/local/etc/dnsmasq.conf

find ~/.valet/Nginx/*.test -type f -exec sed -i '' -e $REGEX {} \;
find ~/.config/valet/Nginx/*.test -type f -exec sed -i '' -e $REGEX {} \;
```

**Comment by drbyte** [comment]
@charpun to clarify, I gather you mean that your users need to run that script anytime they login to their Mac as a different user, right?

**Comment by simplenotezy** [comment]
I am really interesting in a solution to this constantly recurring issue with multi users on macos. As per following source: https://github.com/drduh/macOS-Security-and-Privacy-Guide#admin-and-standard-user-accounts having at least two users (one admin, one "normal" account) is recommended, and thus valet ought to take this into consideration on installation guides / etc

**Comment by timgavin** [comment]
I create a Sites directory in the second user account at `/Users/username/Sites` and put my sites into that, then just head back to my main (admin) account where Valet is installed and run...

```bash
$ cd /Users/username/Sites/foldername
$ valet link foldername
```

... and I can now access that site in a browser from my main account and the user account.

**Comment by mattstauffer** [comment]
I'm going to close this issue; it's good for folks to share their solutions that help them, but I don't think we're planning any big changes going forward that will impact the issue.
