### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT Chrome with Valet

### ISSUE THREAD

**Issue by maliksvd** [laravel/valet#611]
Hi,

I configure Valet for my project, but when i go to adresse i have a chrome error.

DNS_PROBE_FINISHED_NXDOMAIN

PHP version : PHP 7.2.8

**Comment by drbyte** [comment]
NXDOMAIN stands for "non-existent domain"

Basically in the case of Valet it means your dnsmasq service is probably not running, or is not configured to resolve domains ending in the TLD you've used for your project.

Perhaps you haven't configured Valet using `valet park` to specify directories to use for your projects.
Perhaps you haven't configured Valet using `valet domain` for the TLD you're trying to use. It defaults to `.test` which is what you really should be using if you don't want to clash with other real TLDs.

You didn't indicate the domain/tld you were attempting, nor whether this problem is occurring for all projects or just a specific one.

**Comment by maliksvd** [comment]
Ok, but now i have an ERR_CONNECTION_TIMED_OUT

**Comment by maliksvd** [comment]
So i don't unterstand what does not work.

I have update all : 

- PHP 7.2.8 with Xdebug v2.6.1, with Zend OPcache v7.2.8.
- Laravel Valet 2.0.12
- Nginx/1.15.2
- Composer 1.6.5
- Dnsmasq version 2.79

I use a Local Driver for Wordplate (https://wordplate.github.io/docs/installation) but this is no problem because without the driver it does not work either and the problem does not come from Wordplate.

I have `valet park` the folder of my project and i secure with `valet secure`.
But I also tried with `valet link`.

After this i have always chrome/mozilla/safari error "ERR_CONNECTION_TIMED_OUT"

When I ping project.test i have this :  

PING project.test (192.168.50.5): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- pragane.test ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss

So I don't understand where is the problem ?
.

**Comment by drbyte** [comment]
I think your dnsmasq is still not active. When you `ping project.test` it should resolve to 127.0.0.1 not 192.168.x.x  (the ping request may still timeout since the internal firewall may not be set to respond to pings, but the IP address should show as your localhost)

It suggests to me that dnsmasq isn't running. 
What does `brew services list` show? 
When did you last reboot? What does `brew services list` show after the reboot?

In your Mac's System Preferences->Networking->DNS page, what do you have listed for DNS IPs?

You may find my custom configuration for dnsmasq beneficial, as posted in comments in these related issues:
https://github.com/laravel/valet/issues/299#issuecomment-274177318
https://github.com/laravel/valet/issues/115#issuecomment-241275816

**Comment by maliksvd** [comment]
`brew services list` return this ![
](https://i.imgur.com/lQ1q0TB.png)

And for the Mac DNS this is 192.168.1.254

**Comment by drbyte** [comment]
dnsmasq needs your Mac's DNS pointed to localhost, like this:

<img width="455" alt="screen shot 2018-08-02 at 9 05 36 am" src="https://user-images.githubusercontent.com/404472/43585538-605168d2-9633-11e8-9197-72d9d752e379.png">

**Comment by maliksvd** [comment]
I test with your custom configuration and i had dns 127.0.0.1 and i have always the ERR_CONNECTION_TIMED_OUT

**Comment by drbyte** [comment]
You could also enable logging in the dnsmasq config file and then review the logs to see what it's saying. I'm guessing you'll find nothing in it since I think your Mac is still not sending requests thru dnsmasq. 

I don't think this is valet-specific. 
You may find stackoverflow and dnsmasq troubleshooting sites (be sure to specify Mac) to be helpful in sorting out your issue.

**Comment by adamwathan** [comment]
Closing this as not an issue with Valet itself since there's no code we can add to the project that is going to solve this for you. Feel free to continue the discussion to try and troubleshoot your problem though!

**Comment by vladimir-xaro** [comment]
I had the same problem, Chrome was showing this error and FireFox was working fine.
The solution was to change dns in Chrome settings:

![image](https://user-images.githubusercontent.com/72949972/108500790-5d081f00-72c1-11eb-92f1-917443d90e10.png)

**Comment by mkwsra** [comment]
My issue was the same as  @vladimir-xaro , however, I was using Google's DNS instead of Cloudflare, which caused the problem, so boys please stick with "With your current service provider"
![image](https://user-images.githubusercontent.com/1743919/144105033-0c7df6d2-2583-497c-ba0c-e012fc0ce4fa.png)

**Comment by sawirricardo** [comment]
@vladimir-xaro @mkwsra Are there other ways? I need to still use dns in my chrome though.
