### ISSUE TITLE
Valet fails to serve mixed case (CamelCase) folders on case sensitive file systems

### ISSUE THREAD

**Issue by jackfruhecolab** [laravel/valet#622]
### Valet fails to serve mixed case (CamelCase) folders on case sensitive file systems

Example: 

Our parked folder has 3 projects:
````
LARAVELPROJECT1
LaravelProject2
laravelproject3
````
`LARAVELPROJECT1` and `LaravelProject2` do not work under valey and return a `404`

Both will work if they are renamed to all lower case.

### Steps to recreate
**Do not change your primary drive to case sensitive!**

1) Make a case sensitive 'sparseimage volume'
Apple Disk Utility ->New image->Blank Image, and choose `Mac OS Extended (Case-Sensitive, Journaled)`

When you are done with this step, you should see this new volume on the desktop (the default name was `untitled` if you didn't change it.

2) Open terminal
`cd /Volumes/untitled` (replace 'untitled' with your volume name if you gave it a different name)
`valet park`
`laravel new MixedCase`

3) open browser to http://mixedcase.test

4) observe 404 error -this is from the web server.

5) rename /Volumes/untitled/MixedCase to /Volumes/untitled/mixedcase

6) open browser to http://mixedcase.test and observe the site works.

**Comment by drbyte** [comment]
@jackfruhecolab I think the solution is to tweak nginx's `location` directive, as mentioned in:
https://stackoverflow.com/questions/15559460/how-to-configure-nginx-to-ignore-letter-case-in-the-host-name
and
http://nginx.org/en/docs/http/ngx_http_core_module.html#location

```diff
-  location ~ \.php$ {
+  location ~* \.php$ {
```

You could test the proof of concept by running `valet link --secure` on a domain you wish to test it for, and then edit the `~/.config/valet/Nginx/domain.test` file it generated for you, using the change above.
You could additionally add it to your `/usr/local/etc/nginx/valet/valet.conf` file.
If you find it works generally, then you could update your valet stub files and re-secure all your domains.

**Comment by drbyte** [comment]
I was wrong. The above "solution" only affects subdirectories.

**Comment by drbyte** [comment]
Nginx adheres to the standard which treats all domain names as case-insensitive, converting them to lowercase all the time.

Valet then receives that lowercase version of the domain.
Then it uses PHP to call either `is_dir()` or `file_exists()` looking for a matching directory in one of the registered Paths.
This will fail because the lookup is done based on the filesystem returning a response according to its case-sensitive vs case-insensitive nature.

I don't think it makes sense to expand Valet to look for every variant of upper/lower case mixed directory names, as that adds a lot of processing overhead.

There's a VERY simple solution though: simply `valet link` the lowercase-version of the domain.

**Comment by drbyte** [comment]
IMO this issue can be closed.

**Comment by scottgrayson** [comment]
If valet is unable to handle case sensitive file systems, could the workarounds be added to the documentation? Or could we have some warning messages when running valet commands?

This caused me a few hours worth of frustration.
