### ISSUE TITLE
Update valet fails to display my sites

### ISSUE THREAD

**Issue by Treggats** [laravel/valet#640]
OSX: 10.13.6
Composer version 1.5.2 2017-09-11 16:59:25
PHP 7.1.14
Dnsmasq version 2.77
Valet 2.1.1

After updating to valet 2.1.1, the output was the same as for [Kristoffer](https://twitter.com/Hmazter/status/1042411667257262081)

I did an additional, (read in the release notes later that this was perhaps uneccassary)
- valet uninstall
- valet install

But if I try to visit one site, I get an `ERR_CONNECTION_REFUSED`

```
http: error: ConnectionError: HTTPConnectionPool(host='testproject.valet', port=80):
Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10dbfb710>: 
Failed to establish a new connection: [Errno 61] Connection refused',)) while doing GET request to URL: testproject.valet
```

**Comment by Treggats** [comment]
## `valet links`

Tonko--JVDmedia.local | ~ ツ valet links
```
+----------------------------+-----+-----------------------------------------+---------------------------------------------------------------------+
| Site                       | SSL | URL                                     | Path                                                                |
+----------------------------+-----+-----------------------------------------+---------------------------------------------------------------------+
| wordpress                  |     | http://wordpress.valet                  | /Users/tonkomulder/Code/wordpress                                   |
```
Amonst others

## Valet tld
```
Tonko--JVDmedia.local | ~ ツ valet tld
valet
```

## Brew services list
```
Tonko--JVDmedia.local | ~ ツ brew services list
Name       Status  User        Plist
dnsmasq    started root        /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb    stopped
mysql      error   tonkomulder /Users/tonkomulder/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx      started root        /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@5.6    stopped
php@7.0    stopped
php@7.1    started root        /Library/LaunchDaemons/homebrew.mxcl.php@7.1.plist
postgresql stopped
redis      started root        /Library/LaunchDaemons/homebrew.mxcl.redis.plist
```

**Comment by drbyte** [comment]
@Treggats wrote:
> But if I try to visit one site, I get an `ERR_CONNECTION_REFUSED`

You said "visit one site". By that choice of wording, are you saying that "most of my valet sites work, except this one"?

When I've run into a situation like that it's been because there was a specific site config file for it that was somehow damaged. Something like the following resolved it quickly:
```sh
cd FOLDERNAME_OF_SITE_FILES
valet unsecure
valet unlink
valet link
valet secure
```

**Comment by Treggats** [comment]
I meant to say that none of my sites work.
I've followed your quickfix for another site (tried it before with the site I was working on)

```
Tonko--JVDmedia.local | ~ ツ cd Code/wordpress
Tonko--JVDmedia.local | wordpress ツ ls
index.php            wp-activate.php      wp-comments-post.php wp-content           wp-links-opml.php    wp-mail.php          wp-trackback.php
license.txt          wp-admin             wp-config-sample.php wp-cron.php          wp-load.php          wp-settings.php      xmlrpc.php
readme.html          wp-blog-header.php   wp-config.php        wp-includes          wp-login.php         wp-signup.php
Tonko--JVDmedia.local | wordpress ツ valet unlink
The [wordpress] symbolic link has been removed.
Tonko--JVDmedia.local | wordpress ツ valet link
A [wordpress] symbolic link has been created in [/Users/tonkomulder/.config/valet/Sites/wordpress].
Tonko--JVDmedia.local | wordpress ツ valet open
```

Upon opening the site after this, I'm still greeted with the same error.

I've removed the cache/vendor directory, composer dump-autoload, etc.. But none seem to have any effect. Also not sure how I can debug this

**Comment by drbyte** [comment]
> I meant to say that none of my sites work.

Sometimes it helps to double-check your Mac's networking settings to ensure they've got `127.0.0.1` listed as the primary DNS source, so that dnsmasq can be the one providing localized results.

A couple things to try, which also help to rule out possibilities:

1. Is your `WordPressValetDriver.php` customized in any way?
2. If you run `valet link wp2` (or some other non-likely-to-conflict-with-anything name) does the same error occur?
3. If you switch from using `.valet` as your tld to the default of `.test` does the problem resolve?

Also, in your first post above you quoted some error messages: 
> http: error: ConnectionError: HTTPConnectionPool(host='testproject.valet', port=80):
Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10dbfb710>: 
Failed to establish a new connection: [Errno 61] Connection refused',)) while doing GET request to URL: testproject.valet

What app was the source of those messages?

**Comment by pyropoptrt** [comment]
I wasn't having your exact issue but I kept getting the refused connection error. I had to change the config in /usr/local/etc/php/7.1/php-fpm.d/www.conf and /usr/local/etc/nginx/valet/valet.conf because it was pointed to the wrong socket file. 

Log file which pointed me to the issue:
~/.config/valet/Log/nginx-error.log

Configuration files changed:
/usr/local/etc/php/7.1/php-fpm.d/www.conf
/usr/local/etc/nginx/valet/valet.conf 

I had to change the socket path from:
/Users/username/.valet/valet.sock
to:
/Users/username/.config/valet/valet.sock

**Comment by Treggats** [comment]
@drbyte I used httpie to get the testproject.valet url

Now the weirdest thing happend, yesterday I reverted to the previous version of valet, and because I wanted to try @pyropoptrt solution I updated valet again. 
But now, the different sites seem to work.

**Comment by drbyte** [comment]
Did you happen to do a reboot in between? Often that clears up unexpected conflicts.

Glad you got it sorted. If it's working properly, please close this issue.

**Comment by Treggats** [comment]
@drbyte I reverted yesterday, shutdown my mac. and updated today.

Anyway, it's working now. So closing the issue
