### ISSUE TITLE
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by simplenotezy** [laravel/valet#647]
When I run `valet` I get the following error:

	[constantsolutions:/Users/simplenotezy/Projects]$ valet
	PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
	PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
	PHP Parse error:  syntax error, unexpected 'pdo_pgsql' (T_STRING), expecting ',' or ')' in Command line code on line 2
	Password:
	constantsolutions is not in the sudoers file.  This incident will be reported.

I have tried reinstalling several times.

**Comment by drbyte** [comment]
Your `PHP Parse error` sounds like a PHP version mismatch. I suspect your Mac has an older PHP version that's running as primary, and your Terminal path hasn't been updated to insert the Brew version of PHP as the first detected one. 
Running `which php` will tell you which one is "currently" being resolved.
Running `brew info php` will display a bunch of info, including a line to add to the front of your environment `PATH`.

The `Module already loaded in Unknown on line 0` is typical of PHP configurations where php modules are getting re-loaded due to extra config directives. This may go away after resolving which PHP version you're using.

**Comment by drbyte** [comment]
@simplenotezy Is this still a problem? or can this be closed?

**Comment by bramus** [comment]
Had the same thing happening to me after upgrading an already installed a PECL extension (`grpc` in my case).

Check the contents of your `php.ini` (find it by running `php -i | grep .ini`). You'll most likely find double entries for the module `pdo_pgsql` in there.

Remove the duplicate lines and then run `valet restart`. The error should be gone.

**Comment by drbyte** [comment]
Seems like this was a local config issue, and can be closed.
