### ISSUE TITLE
DNSMasq config issue when switching MacOS user

### ISSUE THREAD

**Issue by ravenberg** [laravel/valet#655]
Hi folks, wonderful tool, using it since its beginning! I encountered this issue:

Had to delete my existing MacOS user including the home folder and created a new one. Did a fresh install of Valet on the new user. Including all the services installed by brew. But none of the sites resolved under .test or any made-up domain for that matter.

After digging it turned out that the `/user/local/etc/dnsmasq.conf` file still carried the entry for the `conf-file` of the old (deleted) MacOS user. Even though the conf-file entry for my new MacOS user was beneath it, DNSMasq was unable to do its job. 

To fix it I had commented it out as such
```
# conf-file=/Users/{OLD_USER}/.valet/dnsmasq.conf
conf-file=/Users/{NEW_USER}/.valet/dnsmasq.conf
```

I can not fathom the complexity of setting up multi MacOS user support. But I think writing a check to prevent pointing to the wrong conf-file during install/fix command would be well suited :)

**Comment by drbyte** [comment]
> I can not fathom the complexity of setting up multi MacOS user support. 
 
Ya, multi-user support doesn't work well since all these services are designed to serve from specific users, and permissions are necessarily restrictive. It's challenging shoehorning server-OS behavior onto a non-server-OS environment.

> the `/usr/local/etc/dnsmasq.conf` file still carried the entry for the conf-file of the old (deleted) MacOS user. Even though the conf-file entry for my new MacOS user was beneath it, DNSMasq was unable to do its job.

Thanks for posting and sharing for others to find. 

@charpun posted a brief bash script you could use to cleanup a few things after having switched users: https://github.com/laravel/valet/issues/598#issuecomment-430005592

**Comment by drbyte** [comment]
given a workaround is posted, I suggest closing this.
