### ISSUE TITLE
feature request: cleanup command

### ISSUE THREAD

**Issue by eFrane** [laravel/valet#659]
First of: Valet has been awesome forever. So thank you for that.

One thing I regularly find lacking is some kind of cleanup workflow for getting rid of unused configuration. The motivation is that I don't always think about valet when I purge projects I don't currently work on from disk. This, unfortunately, leaves the valet configuration lying around. Another case is renaming a project folder after the valet link has already been made.

Granted, these files are negligible in size and it might even be seen as a feature to keep the config. Also, I could just use `valet path` instead of `valet link`. However, I don't see any damage being done in offering a `valet cleanup` command which checks for the existence of the configured links and paths and removes obsolete configuration, log files, etc.

I would happily provide a PR if this is a desired feature.

**Comment by drbyte** [comment]
Hi @eFrane Valet 2.6.0 introduced a new `valet uninstall --force` command which does an aggressive full removal of everything. While it's not a general "cleanup while Valet remains fully installed and functioning", it is a full nearly idempotent cleanup, and a subsequent `valet install` should do a fresh clean install and setup.
You could backup your `~/.config/valet` folder if you had any concerns before it purged things.

**Comment by eFrane** [comment]
I flat out forgot about that issue :see_no_evil:.

@drbyte Hm. While also usefule, that's a different functionality from what I was describing. But seeing that there are thumbs up emojis now, I hereby renew my offer to implement this feature myself. 

Please @ me, if this is desired and I will prioritise the implementation on my to-do list.

**Comment by drbyte** [comment]
@eFrane I like the idea of cleaning up outdated links and certificates for purged/removed projects. 
(Not sure about your mention of log files since Valet doesn't generate site-specific log files.)

I'd suggest calling the command `valet cleanup-links` so that it's more clear about what it's "cleaning up", and not confused with other cleanups that an uninstall would do.

There were some recent improvements to the `valet parked` and `valet links` commands to output more thorough information about which sites Valet can/does serve. Some of the underlying code for those may be particularly useful in your interests around cleaning up links to no-longer-available projects. Perhaps cloning some of it and using an opposite collection filter (to "keep" missing dirs, instead of "rejecting" missing dirs) may fast-track dev work.

I suggest also including a call to `valet unsecure [domain]` on any links your code would propose removing, so that the certificates are removed not only from the Certificates dir and Nginx configs dir but also from the Keychain certificate vault as well. 
(Aside: You can run `valet uninstall` since v2.6.0 to have it explain more about how to do manual cleanups of leftover certs in your Keychain.)

Also, a tip: a handy way to create a new command and test it, is to build it as an Extension to Valet, which you put into the `~/.config/valet/Extensions` folder, instead of having to tinker in the global composer directory tree. Here's an example for inspiration:
`~/.config/valet/Extensions/show-config.php`:
```php
<?php
namespace Valet;

use function Valet\info;

$app->command('show-config', function () {
    $config = new Configuration(new Filesystem);
    info('Valet configuration: ' . $config->path());
    passthru('cat ' . $config->path());
})->descriptions('Display Valet config JSON file contents');
```
