### ISSUE TITLE
Port 88 already in uses / site refuses to connect

### ISSUE THREAD

**Issue by alloyking** [laravel/valet#671]
Fresh install of Valet.  Unsecured sites work fine under .test or the like.

When the sites are switched to .dev and valet secure is run.  The nginx configuration has a server set-up for port 80, 443 and 88.   Nginx throws errors that port 88 is already in use.

I wouldn't care too much except that the site fails to load.  If I remove the server configuration in nginx for port 88 everything works.

**Comment by drbyte** [comment]
This appears to be a duplicate of the report of Kerberos Screen Sharing conflict at 
https://github.com/laravel/valet/pull/630#issuecomment-437593570
.. which was fixed by https://github.com/laravel/valet/pull/670
... which was merged into dev-master today.

It would be helpful if you change your valet install to use dev-master to test it out and give feedback before we tag the next official release. 
To do that, use:  `composer global require laravel/valet:dev-master` and then `valet install` and maybe `valet restart` in case some of your services need a restart.

**Comment by pix2D** [comment]
@drbyte The fix works for me, thanks!

**Comment by alloyking** [comment]
@drbyte This has worked for me as well.  Thank you.
