### ISSUE TITLE
Do I need a custom WordPress Driver or Ngnix rule for url rewritting?

### ISSUE THREAD

**Issue by Danny-G-Smith** [laravel/valet#686]
I want to rewrite a url that looks like: **shortcode.5.0.1.css** rather than **shortcode.css?ver=5.0.1**

I have tried adding this to the nginx config file, but am not sure where to put it.

    # START - REWRITE ASSET VERSIONS
    location ~* (.+)\.(?:\d+)\.(min.js|min.css|js|css|png|jpg|jpeg|gif)$ {
      try_files $uri $1.$2;
    }
    # END - REWRITE ASSET VERSIONS

**Comment by drbyte** [comment]
I won't comment on the actual rewrite rules, since that's part of your app/domain.

But as far as "where to put" nginx configs for your specific site in valet, the `~/.config/valet/nginx/` directory is where you would find your site's nginx configs. If your site isn't listed in there, in terminal go to that app's project directory and run `valet link` to create it (or/and if you want SSL on it, run `valet secure`). Then add your custom nginx statements.

Be aware that that nginx directory is semi-volatile, in that running `valet link` / `valet secure` on that project, or running `valet tld` or `valet domain` or `valet install` will overwrite all your nginx configs.

**Comment by riskiii** [comment]
Yes I am sorry, it can be closed.  

cheers,
Danny
