### ISSUE TITLE
Allow a reverse proxy for websockets to work.

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/valet#697]
Would someone be able to tell me if I can do the following with Valet.

I had previously on my windows machine (using Homestead), the following setup for my Laravel app using `laravel-echo-server`.

Rather than having to open multiple firewall ports for my app and the Laravel echo server....and then having to manage the SSL certificates for the echo server and update the config file whenever LetsEncrypt renewed the certificates - I used a reverse proxy to bypass a lot of the config headaches.

Using this code in the nginx conf for my app
 ```
// In your nginx setup for your website eg
//  /etc/nginx/sites-enabled/example.com, in the server block add the following

location /socket.io {
    proxy_pass http://127.0.0.1:6001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}  
```

This allowed the user to connect to my website using normal SSL, then when the connection tried to access the url `/socket.io` nginx would then grab the packet and proxy it to the localhost echo server without the need to worry about SSL and certificates for that portion of the connection.

(More expansive explanation [here](https://github.com/tlaverdure/laravel-echo-server/issues/164#issuecomment-309214294) )

Now however since moving to valet on my new Macbook I can't recreate this setup and my development has come to a screeching halt.

Valet doesn't seem to have a nginx conf file for each site. So I can't add the above code to a `.conf` file.

How can I tell valet that any incoming connection to a specific URL should be forwarded/proxied like above to another local server (ie echo server or spaties new websockets server).

In fact the new websockets package has a section dealing with valet, [here](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-laravel-valet) but it still involves setting up certs etc and that won't match with the production server when the code is uploaded. I'd love to just have a simple proxy solution like I had in homestead.

Any kind of push in the right direction would be most welcome.

Thank you.

**Comment by drbyte** [comment]
@jonnywilliamson wrote:
> Valet doesn't seem to have a nginx conf file for each site. So I can't add the above code to a .conf file.

If you go into your app/project directory and run `valet link` it will create a .conf file (without the .conf extension) in your `~/.config/valet/Nginx` directory, which you can customize. Do be aware that it also replaces this file if you run certain valet commands such as install, secure, or tld.

You might want to take a different approach, where you edit the `~/.composer/vendor/laravel/valet/stubs` files since that's what valet rebuilds conf's from.

**Comment by jonnywilliamson** [comment]
@drbyte 

Thank you so much for that information! That's such a help.

I haven't got everything working just yet, but the websockets are now connecting which is such a jump forward from where I was.


Much appreciated.

**Comment by jonnywilliamson** [comment]
@drbyte 

Not that its an issue, but I can only get a `.conf` file to appear in the `Nginx` folder if the site is secured. If I have an unsecured site and run `valet link` I don't get a `.conf` file.

Is this proper behaviour? As I said I don't really mind needing to secure the site, but I was just wondering.

**Comment by drbyte** [comment]
@jonnywilliamson, my bad. You are right: you must secure the site for the .conf file to be generated.

**Comment by drbyte** [comment]
I should also point out that if you've elected to edit the stubs, that your changes to the `.composer/vendor/...` directory are also volatile, as they are replaced when running `composer global update`. 
TIP: You can save yourself some pain with this by using `dev-master` since that'll turn it into a git repo which can stash/unstash when doing `composer global update` interactively. It'll recognize that you've made customizations and offer you the choice to overwrite or stash/unstash when applying updates.

**Comment by jonnywilliamson** [comment]
@drbyte That's a nice tip thank you.

**Comment by skeemer** [comment]
Can we get a stable way of adding proxy_pass? It seems that all of the ways to handle this are volatile.
Maybe a custom stubs directory just like the custom driver directory?

**Comment by jonnywilliamson** [comment]
> @jonnywilliamson Does this need to be kept open?

Not from me. It's working the way I need at the moment.

Thanks again.
