### ISSUE TITLE
Question about mailcatcher and Valet

### ISSUE THREAD

**Issue by benlk** [laravel/valet#698]
I'd like to be able to stop outgoing mail from my Valet sites, using [mailcatcher](https://mailcatcher.me/) or something similar. Mailcatcher provides PHP sample php configs for php.ini or Apache, and [this gist](https://gist.github.com/Luminus/e5d8149df1c70ef121f07cd42d36e2c1) has a sample for a particular site's Nginx conf file.

However, I'm taking advantage of valet's [park](https://laravel.com/docs/5.6/valet#the-park-command) command, which serves distinct sites for every folder in a directory. I've looked in `/.config/valet/`, and only sites that have been `valet secure`'d or `valet link`'d have configuration files in `/.config/valet/Nginx/` or `/.config/valet/Certificates/`.

My questions are:

- Is there a way to enable Mailcatcher for all Valet sites by editing a single Nginx or PHP configuration file?
- If the one-and-done approach isn't possible, is there a way to edit one config file that will affect all sites not in `/.config/valet/Nginx/`? I think I'd have to edit all sites in `/.config/valet/Nginx/` as well, under this scenario.
- Or do I have to `valet secure` or `valet link` each site (about 60 sites) that I want to have covered by mailcatcher?

**Comment by ihorvorotnov** [comment]
I'm using mailhog, works fine. Just run:

`brew install mailhog`
`brew services start mailhog`

Add this to some custom php config in `conf.d` dir (I use `php-custom-settings.ini` file);

```
[sendmail]
; Use Mailhog
sendmail_path = mailhog sendmail
sendmail_from = server@localhost.test
```

and then `valet restart`.

**Comment by drbyte** [comment]
2 approaches you can take:

1. Add a custom php.ini conf.d file, similar to what @ihorvorotnov suggested.
You only have to do this once per PHP (major) version you install.
Create a new file: `/usr/local/etc/php/7.3/conf.d/mailcatcher.ini`
(replace the `7.3` with your PHP version, and put a copy of this file in all PHP versions you want affected)
Contents of the file, based on the gist you mentioned, would be:
```ini
[sendmail]
sendmail_path=/usr/bin/env PATH/TO/catchmail -f admin@wctest.dev
```
Of course, change paths and email addresses to suit your setup.

2. Edit the nginx fastcgi parameters config.
This is more volatile because it gets overwritten when you upgrade Valet and run valet install to bring yours up to date. So, you'd have to re-apply your change after doing such a step.
Edit the `/usr/local/etc/nginx/fastcgi_params` file and add your mailcatcher directive there (ref the gist you mentioned).
(This file comes from the stub in `~.composer/vendor/laravel/valet/cli/stubs`, but as I said, it gets replaced when you upgrade valet.)

**Comment by drbyte** [comment]
@benlk did this work for you?

**Comment by drbyte** [comment]
IMO this can be closed.
