### ISSUE TITLE
Phpunit tests not picking up phpunit.xml config

### ISSUE THREAD

**Issue by matthewsuan** [laravel/valet#723]
All my phpunit feature tests failed and upon looking closely, the phpunit.xml file is not picked up during testing so all http tests have 419 errors and actual dev database gets wiped out.

Its picking up env values from `.env` file

I even tried to set the path to the config file manually but still fails: `$ phpunit --config phpunit.xml`

I am running latest Valet version Mojave.
PHP: 7.3
Phpunit: 7.5.2
Laravel: 5.7

This only happens on Valet. Application works fine though and only testing is affected.
Running the tests on Homestead with the same application codebase works fine.

I also tried restarting Valet and rebooting my machine.
Also tried config:clear and cache:clear to no avail.

One weird thing too is that inspecting `env` value from tinker does not return correct results after deliberately changing it from `.env` file. [Of course I restarted tinker upon doing it].

Thanks for any help.

**Comment by drbyte** [comment]
This doesn't sound like a problem with Valet specifically. Valet essentially just provides a way of redirecting http local traffic to configured local directories/projects, and configuring PHP to be called where needed.

What you're talking about is problems at the command-line. Most of the time when you get unexpected results at the command-line, it's related to incorrect environment PATH, incompatible packages (either homebrew pkgs or php/laravel pkgs) installed, or things in your own app which are interfering with your expected results.

In the case of your phpunit problem, what phpunit binary is running? Is it loading from your laravel app, or is it loading from the composer-global space? What happens if you specify a complete path to your config file instead of providing no path? 

And, if you were to ask someone else to recreate your exact same app, to create the exact same problem, what exactly would they have to do to make the problem happen? (ie: reverse engineer what problem might actually be in your own app, including starting with a new Laravel app on your machine, with no custom code or configs, just a fresh install, and running the default test suite tests on it, and slowly adding things into it until it breaks). Tell us what you uncover by doing that!

**Comment by matthewsuan** [comment]
hey guys. this is now resolved. I restarted my machine the second time with updates installed and the issues disappear. ty @drbyte
