### ISSUE TITLE
Stuck on PHP Version 7.2.15 after using valet use php72

### ISSUE THREAD

**Issue by lasseeee** [laravel/valet#728]
After upgrading valet to v2.2.1 and running `valet use php72`, I'm stuck on php 7.2.15 no matter what I do. Running  `valet use php73` does nothing. Tried uninstalling and reinstalling valet via composer as well as all php version using brew. After uninstalling all php version through brew, `phpinfo()`still works through valet and shows version 7.2.15, so it seems to be stuck somehow on default it's internal php version. Any ideas how I can bump it back up to php 7.3?

**Comment by drbyte** [comment]
Valet only works with homebrew-installed PHP versions, not the default one that comes with OSX. (Aside: This is currently intentional, because of the many related services that need to be configured, and the pre-installed OSX applications don't fit well.)

To make sure the homebrew-installed PHP version is used, you need to do as Homebrew says and add the Homebrew version of PHP to your PATH variable, and also `brew link php`. You can test this by running `which php` to determine whether it's pointing to the correct location.

To be clear, you also need to be using homebrew without customization overrides which put apps or configs in non-standard locations.

**Comment by mattstauffer** [comment]
In case @drbyte's suggestions don't help, there's a reallllllly edge-y edge case that is almost definitely not what you're running into, but I'll throw it in here just in case.

https://twitter.com/JoseCanHelp/status/1093553875850850312

**Comment by lasseeee** [comment]
Still stuck on 7.2 after doing `valet use php72` and then trying `valet use php73` or `valet use php71`.

Trying to move back down to php 7.1 by running:

```
brew install php@7.1
brew unlink php@7.1 && brew link --force --overwrite php@7.1
```

and then

```
echo 'export PATH="/usr/local/opt/php@7.1/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="/usr/local/opt/php@7.1/sbin:$PATH"' >> ~/.zshrc
```

and then

`valet use php71`

but phpinfo still returns 7.2.15, even though `which php` returns `/usr/local/opt/php@7.1/bin/php` and `php -v` returns PHP 7.1.25.

How come valet is stuck on php 7.2.15 still?

**Comment by drbyte** [comment]
> phpinfo still returns 7.2.15

When you say "phpinfo still returns...", I assume you mean a phpinfo command being run from a web app, processed via nginx or apache? (as opposed to the command line which `php -v` or `php -i` gives).

> How come valet is stuck on php 7.2.15 still?

Probably because you haven't run `valet install` after installing your custom PHP version.

The normal configuration of valet, when displaying web apps, uses dnsmasq to intercept the registered TLD and serve the corresponding project directory via the nginx configuration that valet has customized. It relies on PHP being configured to listen on `valet.sock`, and then the nginx config uses the `valet.sock` socket to provide PHP-FPM passthru for PHP processing.

More specifically, your running PHP-FPM instance (that is, specifically the PHP version you want Valet to use) needs to be creating the valet.sock file successfully. If this is created by a different PHP version, then that's what'll be used. The version "running" is determined by what you have running in homebrew, reviewable with `brew services list`.
Additionally, if your php.ini hasn't been updated with the valet-specific settings that `valet install` makes, then it won't know to create the `valet.sock` file which nginx uses.

**Comment by lasseeee** [comment]
You're right.

`brew services list` showed that php@7.2 was erroring out. Deleting the .plist for php 7.2 in `~/Library/LaunchDaemons/` and reinstalling via brew solved the problem. I can change freely between php version now. Thank you.

It does, for the record, always says `[php@7.3] is not installed, installing it now via Brew... 🍻`whenever i run `valet use php73`. It does work flawlessly tough.

Thanks again.

**Comment by mattstauffer** [comment]
@drbyte I didn't follow this the whole way (don't judge me!)--is there anything we should change or document in response to this? Thanks!!

**Comment by drbyte** [comment]
@mattstauffer ya, the last comment exposes a small glitch in the php version switching, caused by Homebrew's aliasing:

Homebrew treats `php` as equiv to `php@7.3` and `php73`
The `valet use php73` command greps `brew list` for `php73` but only finds `php` so it thinks it needs to install it.
We could do better aliasing in our `Brew::installed()` code. But I think that warrants being a separate issue than the one initially discussed here.

**Comment by mattstauffer** [comment]
Ahhhhh got it. Will create a new issue and y'all can clean it up if I didn't represent it well.

**Comment by magedevjosh** [comment]
> In case @drbyte's suggestions don't help, there's a reallllllly edge-y edge case that is almost definitely not what you're running into, but I'll throw it in here just in case.
> 
> https://twitter.com/JoseCanHelp/status/1093553875850850312
> 
> > .@LaravelPHP Valet wasn't detecting any of the changes I made to php.ini. Restarting brew services and restarting Valet had no effect. Turns out the valet.sock file was being persisted and somehow caching settings. `rm ~/.config/valet/valet.sock` solved my problem! 🙌🏽

This fixed my issue. Spent the past 30 minutes uninstalling and reinstalling services via brew to no avail.  Thanks, @mattstauffer!

**Comment by websmyth** [comment]
@magedevjosh That just fixed it for me, too. Hours of Googling and hair-tearing later, but thankful for the fix nevertheless! 🙌

**Comment by lasseeee** [comment]
For anyone landing here, future me included: Remember to check your $PATH for php versions
