### ISSUE TITLE
Support for php@5.6

### ISSUE THREAD

**Issue by SimonJ** [laravel/valet#742]
I've trying to switch my PHP version to `5.6` but it seems like brew is not hosting that version anymore.
I have a client that is using version 5.6. so is there anything we can do? 

Maybe use another host if people are trying to downgrade to that version?

**Comment by ahinkle** [comment]
This ins't really anything to do with Valet as Valet uses brew to handle the PHP versions I suppose you can use PHP 5.6 in other means such as Docker or installing it locally.

**Comment by ahinkle** [comment]
This isn't really anything to do with Valet as Valet uses brew to handle the PHP version switching. PHP 5.6 is deprecated and therefore unsupported by brew's support policy.

I suppose you can use PHP 5.6 in other means such as Docker or installing it locally.

**Comment by josecanhelp** [comment]
@SimonJ Yea, unfortunately, this isn't something that should be resolved within Valet itself. However, I was intrigued with how to best move forward with someone wanting to use PHP 5.6 within brew. I created a tap that is publicly available. It should help out.

If you run `brew tap josecanhelp/php56`, then you will be able to command valet to install PHP 5.6 and use it with `valet use php@5.6`.

The issue comes in where valet itself has some dependencies that are not compatible with PHP 5.6. So even running valet with PHP 5.6 is not possible without modifying the dependencies. The two dependencies that cause this are `illuminate/container` and `tightenco/collect`. The following would resolve this:

```json
"require": {
        "illuminate/container": "5.1 - 5.4",
         ...
        "tightenco/collect": "5.3 - 5.4"
    },
```

However, I'm not sure how best to PR that change into valet or if @taylorotwell would even want to merge this in and create a tag just to support an EOL version of PHP.

For the time being, you could uninstall valet (remove it from your global dependencies) and force require my fork by modifying your global `composer.json` like so:

>~/.composer/composer.json
```json
{
    "require": {
        "josecanhelp/valet": "dev-php56"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/josecanhelp/valet"
        }
    ]
}
```

I cannot guarantee that this won't conflict with some other global dependencies you have, but hit me up if you come across any issues.

**Comment by SimonJ** [comment]
Thanks a lot @josecanhelp ! gonna try this later

@ahinkle I know it has nothing to do with Valet, but I still think people are using PHP 5.6 on some older projects. I just think it would be nice to still be able to use that version and keep it `a blazing fast Laravel development environment ` :)

**Comment by aaemnnosttv** [comment]
There is a bit of discussion on this in a PR of mine from a while back in https://github.com/laravel/valet/pull/535 which may be useful here.

**Comment by drbyte** [comment]
Agreed.

And then I think this issue can be closed.
