### ISSUE TITLE
Issue in using php 7.2 on valet plus

### ISSUE THREAD

**Issue by mira-thakkar** [laravel/valet#779]
When i try to run `valet use 7.2`, it gives me error something like this:

> Apples-MacBook-Air:bin mirathakkar$ valet use 7.2
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
PHP Parse error:  syntax error, unexpected '' - dlopen(/usr/local/lib/php/' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 5
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
PHP Parse error:  syntax error, unexpected '' - dlopen(/usr/local/lib/php/' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 5
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
Could not open input file: 
Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20160303/geoip.so' - dlopen(/usr/local/lib/php/pecl/20160303/geoip.so, 9): Library not loaded: /usr/local/opt/geoip/lib/libGeoIP.1.dylib
  Referenced from: /usr/local/lib/php/pecl/20160303/geoip.so
  Reason: image not found in Unknown on line 0
Parse error: syntax error, unexpected '' - dlopen(/usr/local/lib/php/' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 5/cli/valet.php

Can anyone help me with this, how to resolve this and work with valet-plus

**Comment by mattstauffer** [comment]
Better opened in Valet-plus repo: https://github.com/weprovide/valet-plus

**Comment by drbyte** [comment]
Yes, support for valet-plus should be done in their repo.

In the meantime, since this same symptom happens often with pecl packages when Homebrew upgrades PHP, I offer the following suggestions. 

(Common other pecl packages I've seen affected are memcached, xdebug, and phpredis.)

The "Unable to load dynamic library" error message you're getting is usually because your php.ini has old references to pecl packages that are no longer in the path indicated in your php.ini.
Simplest fix is to go to your /usr/local/etc/php/7.2/php.ini and remove that geoip pecl package line from it. pecl usually puts its stuff in the top of the file.

If you still want it, you can re-install your pecl package afterward, but you may also need to remove the /usr/local/lib/php/pecl symlink if pecl fails to be able to copy its assets there.
