### ISSUE TITLE
‘valet on-latest-version’ command is not working

### ISSUE THREAD

**Issue by miagg** [laravel/valet#796]
On latest valet v2.3.3 running **valet on-latest-version** returns this:

`
/usr/local/bin/valet: line 63:  7892 Segmentation fault: 11  php "$DIR/cli/valet.php" "$@"
`

Probably some kind of issue with **Httpful** library, since I checked the endpoint that Valet.php hits and it works.

I'm on Mojave 10.14.5 (18F132)

**Comment by drbyte** [comment]
Is this the *only* thing with Valet that's giving a `Segmentation fault` message?

It would be ideal if you edited the issue Title with more specificity.

It sounds like you've tried some troubleshooting. Can you explain more about what you've done and what you've discovered?

For me, running `valet on-latest-version` gives back a `YES` response. So, clearly your Mac is behaving differently from mine. How can I make mine just like yours?

Also, since `valet on-latest-version` is not intended for humans to call (it's an internal command), why are you running it?

**Comment by miagg** [comment]
@drbyte I did some digging but didn’t have any more time. I know it’s not a huge deal and it’s possibly related with the latest version of MacOS but I thought you should know. I have non seen any other issues. Maybe there is no need to include it on the help screen if it’s an internal command anyway.

**Comment by drbyte** [comment]
> Maybe there is no need to include it on the help screen if it’s an internal command anyway.

Agreed. I haven't seen a way to exclude it but still have it registered so the command works when called internally.

> **EDIT**: Turns out it's PHP that is crashing

Thanks for confirming. I expected it was probably not actually a Valet issue.
(And you can probably therefore close this issue.)
