### ISSUE TITLE
DNS info missing between sites

### ISSUE THREAD

**Issue by fakingfantastic** [laravel/valet#805]
Hi there, 

I've recently run into a situations where I am trying to communicate over HTTP between two sites hosted by Valet: Site A (WordPress, url: wordpress.test) and Site B (JSON API in Laravel, url: api.test)

When Site A attempts to cURL for api.test, it receives the error "Could not resolve: api.test (Domain name not found)"

Here's some sample code to recreate:
```php
$url = "http://api.test";
$options = array(
    CURLOPT_URL            => $url,
    CURLOPT_RETURNTRANSFER => true
);
$ch = curl_init();
curl_setopt_array( $ch, $options );
$response = curl_exec( $ch );
var_dump(curl_error($ch)); //"Could not resolve: api.test (Domain name not found)"
curl_close( $ch );
```

I was able to fix it by manually adding the DNS entry to `/etc/hosts`
`127.0.0.1      api.test`

..but looking to avoid that

Thanks in advance!!

**Comment by drbyte** [comment]
My first reaction is that it's specific to CURL, so am inclined to suggest putting CURL in the github issue title.

Next, I wonder if CURL is specifically doing DNS queries to public sources first instead of to localhost. To address this, I'd go into your macOS network settings and add 127.0.0.1 as the first DNS resolver. A lot of times this solves any oddities where a subsystem bypasses dnsmasq as in your situation.

<img width="668" alt="OSX DNS config" src="https://user-images.githubusercontent.com/404472/62465940-1e058d80-b75e-11e9-8c4d-2e15beb16c35.png">

**Comment by foundVanting** [comment]
> My first reaction is that it's specific to CURL, so am inclined to suggest putting CURL in the github issue title.
> 
> Next, I wonder if CURL is specifically doing DNS queries to public sources first instead of to localhost. To address this, I'd go into your macOS network settings and add 127.0.0.1 as the first DNS resolver. A lot of times this solves any oddities where a subsystem bypasses dnsmasq as in your situation.
> 
> <img alt="OSX DNS config" width="668" src="https://user-images.githubusercontent.com/404472/62465940-1e058d80-b75e-11e9-8c4d-2e15beb16c35.png">

At first, thanks for your help,but can't  other host unknown.

**Comment by drbyte** [comment]
Update: I tested this using the supplied code example (thanks for that!), and adding 127.0.0.1 to the list of DNS Servers indeed allows it to work.

Given that even the dnsmasq docs recommend adding 127.0.0.1 to the list of DNS Servers (resolvers) as mentioned above, I believe this issue can be closed.
