### ISSUE TITLE
Error when attempting to generate certificate

### ISSUE THREAD

**Issue by cgreuling** [laravel/valet#842]
Getting this error message when running valet secure

macbook-pro-2:test-site chris$ valet secure

In Process.php line 1648:
                                                                                                  
  Command line is missing a value for key "$NF": sudo security find-certificate -e "test-site.test@laravel.valet" -a -Z | grep SHA-1 | sudo awk '{system("security delete-certificate -Z   
  "$NF" /Library/Keychains/System.keychain")}'.                                                   
                                                                                                  

secure [<domain>]

Running macOS Catalina Version 10.15.1

Please let me know if there's anything else I can provide.

**Comment by drbyte** [comment]
This appears to be a duplicate of #810 
I posted some technical commentary there, and offered some things to inspect which may help troubleshoot further, even if only collecting common information to establish trends in order to identify what unique thing these few instances have in common which could be triggering the issue.

**Comment by cgreuling** [comment]
Didn't realize this was a duplicate. Closing.
