### ISSUE TITLE
Update to latest version of mnapoli/silly

### ISSUE THREAD

**Issue by GeoJunkie** [laravel/valet#860]
Currently, valet is pointing to `mnapoli/silly` v 1.0. That references package `container-interop/container-interop`, which has been abandoned and replaced with `psr/container`.

Should Valet move to the latest version of `mnapoli/silly` to maintain currency?

**Comment by drbyte** [comment]
It's actually using `~1.0` which means it'll use anything 1.x.x ... which right now means it's using the latest version.

In my latest fresh install it's loaded mnapoli/silly v1.7.2 ... which, like you said, uses `psr/container`

https://github.com/mnapoli/silly/releases

I'm guessing that your reason for posting this is because *yours* is using an older version?
Perhaps you have other composer global dependencies that are forcing your install to use an older version?
Or is it just that you need to run `composer global update` to make things more current?

**Comment by drbyte** [comment]
IMO this can be closed
