### ISSUE TITLE
valet 2.7.0 with php 7.1 error

### ISSUE THREAD

**Issue by elephantux** [laravel/valet#879]
I need to use php 7.1 with valet, but after ```valet use php@7.1``` valet show error:
```
Fatal error: Declaration of Symfony\Component\Console\Input\Input::getArgument($name) must be compatible with Symfony\Component\Console\Input\InputInterface::getArgument(string $name) in /Users/slon/.composer/vendor/symfony/console/Input/Input.php on line 28
```

```composer global update```
```Nothing to install or update```

Any ideas?

**Comment by drbyte** [comment]
I think you're on the right track with fixing it via composer.

What I'd suggest doing is editing your global composer.json (`~/.composer/composer.json`) and remove everything except the laravel/valet line. 
Then delete your `~/.composer/vendor` folder and your `~/.composer/composer.lock` file.
Then run `composer global update`. 
This process removes all other dependencies or things it compares against, so that it can negotiate the right version of the symfony components suitable for your backdated PHP version.

You could alternatively force some of the symfony components to specific older versions known to be compatible with your older PHP version.

**Comment by elephantux** [comment]
@drbyte thanks for your reply but this don't help. After deleting and global update I got the same error for valet.

**Comment by drbyte** [comment]
@elephantux The only way I can trigger that Symfony Console error is to use mismatched versions for wrong PHP version.

**Comment by flyingkitlets** [comment]
@drbyte Thanks so much, this saved my bacon!

**Comment by drbyte** [comment]
@elephantux Is this still an issue? Or can it be closed?

**Comment by ecrmnn** [comment]
For anyone coming to this issue in the future.
Stumbled upon this myself.

I installed valet while using PHP 7.4 and then tried to use valet after running `valet use php@7.1`.
The solution is to install valet *while* running PHP 7.1

```bash
# Make sure current PHP version is 7.1
php -v

# Then run
rm -rf ~/.composer/vendor &&
rm ~/.composer/composer.lock && 
composer global update
```
