### ISSUE TITLE
Valet 2.7 breaking wp_remote_post calls

### ISSUE THREAD

**Issue by itzikbenh** [laravel/valet#882]
To trigger a background job I make an http call to my own server and all worked fine until I upgraded valet. Now each time I make that call I get back `{"code":"http_request_failed","message":"cURL error 52: Empty reply from server","data":null}`

The call doesn't even hit the PHP file, something stops it beforehand. 
To verify that it's not a code issue I tested the same project on MAMP and it was fine. 
This leads me to believe that something in valet breaks it, but I have no idea what might cause this issue.  I personally haven't configured anything myself. 
Any idea what might cause this issue?

**Comment by itzikbenh** [comment]
I just tested my project in local flywheel as well, works just fine too. Definitely a valet issue. 
The funny thing, if I run `curl  -X POST ....` in the terminal, it does work, as in hitting my `admin-ajax.php` file. Really odd problem.

**Comment by drbyte** [comment]
Wordpress is often having troubles with curl. No idea why. Makes me hate wp more every day.

You didn't say which version of Valet you "upgraded from".

Two possibilities come to mind:
- If the background process is going out-of-band and attempting to come in on another interface besides 127.0.0.1, then perhaps the change made in v2.4.0 via #814 might be blocking access.
- Perhaps your OpenSSL got updated and the CA certificate resolution is failing, in which case updating related config files may help. 

Running `valet install` should reset any PHP/Nginx/Dnsmasq issues. But it doesn't touch curl/openssl or other homebrew services that your wp install might be relying on.

**Comment by itzikbenh** [comment]
I haven't upgraded in a while, so I imagine it was 2.0, or so. I did upgrade OpenSSL, which gave me hell, but this is the only problem left to fix. 

Regarding your first point, does downgrading Valet reverses it? Because I downgraded to 2.1 and issue still remained. 

I'll see what i can google about OpenSSL, thanks.

**Comment by drbyte** [comment]
To test downgrading I think you'd need to upgrade back to 2.7.0 or higher, run `valet uninstall --force` (added in 2.7.0) to have it cleanup all the related configs that it controls. Beware that that aggressively removes almost everything. Then downgrade to an older Valet version and run valet install to see if it works then.  If it doesn't, then it's not likely Valet, but rather OpenSSL et al.

As to OpenSSL you might be able to forcefully remove it via homebrew, and delete the configs for it in `/usr/local/etc/openssl*` (1.0, 1.1, etc). And reinstall. But since it may be required by PHP and/or Nginx things, it may be best to do the openssl removal after doing valet uninstall --force ... and then it'll either be auto-reinstalled (with only the needed version) by homebrew when running valet install to put back the php/nginx components.
Sorry, it's not pretty dealing with these external dependencies. (Which is complicated by the fact that MacOS provides its own openssl which is often older, and can conflict with brew's version.)

**Comment by itzikbenh** [comment]
No luck, even after deleting and reinstalling OpenSSL via brew.
I'll just move on from this, already wasted two days on this nonsense. 
Thanks again for your help.
