### ISSUE TITLE
Suggest updating APP_URL, etc

### ISSUE THREAD

**Issue by fgilio** [laravel/valet#883]
Hello!
I just created a new project and I'm using Valet for the dev environment.
It occurred to me that it would be really helpful to suggest manual configuration steps after a `valet link`, like updating the APP_URL env var for a Laravel app. It should be part of the driver because it will vary with the app. And it could go as far as making the change automatically or maybe asking for confirmation.

What do you think?

**Comment by drbyte** [comment]
I'm not sure that's really a Valet responsibility.

In fact, depending on the kind of apps you build, the APP_URL may not even get used, since a lot of the time Laravel correctly generates links based on the incoming URL, or relative to the current URL.  To be fair, many front-end clients depend on APP_URL because they don't have the awareness that the server-side Laravel app does.

But one must keep in mind that while Valet is certainly used largely for Laravel apps, there are a lotta people using it for non-Laravel projects as well ... and therefore having Valet try to do some Laravel-specific alterations feels slightly too intrusive (and possibly error-prone).

That said, I think it's great that you're exploring ideas that can make one's dev environment more streamlined and more productive. So ... I offer two suggestions: one very simple, and one that lets you flex your coding muscles to create your own custom command in Valet.

## Fastest, simplest way:
Why not just use Tighten's [Lambo](https://github.com/tightenco/lambo) project? 
It will do what you mention, and more, out-of-the-box!

## More personalized, custom command:
You could explore for leveraging this feature within Valet is to write your own custom Command. Valet calls those Extensions.
I envision you'd do something like this:

Create a new file in the `~/.config/valet/Extensions` folder. For example:
`~/.config/valet/Extensions/show-config.php`:
```php
<?php
namespace Valet;

use function Valet\info;

$app->command('show-config', function () {
    $config = new Configuration(new Filesystem);
    info('Valet configuration: ' . $config->path());
    passthru('cat ' . $config->path());
})->descriptions('Display Valet config JSON file contents');
```
 
The above example outputs some information, but you can copy into it the `link` command from Valet core:
https://github.com/laravel/valet/blob/edbc4fc0d3691532c34b85c628aa09bcb9adc3a2/cli/valet.php#L123-L134

... and then add your additional things.

You might even take inspiration from how Lambo does the APP_URL change:
https://github.com/tightenco/lambo/blob/df03adefbb0386c635a7fb2107fd1f89fa1b17f3/lambo#L418-L432

**Comment by fgilio** [comment]
Woohoo, thanks for really getting into it 🤯 🙌 

You do raise a valid point with not being sure if it's a Valet responsibility, and maybe if the action that Valet could suggest is optional (like with APP_URL) then the value added would vary from nothing to low.

I imagine that this would be part of the driver. So Wordpress, Drupal, Laravel, etc could each heave it's own suggestions. But tbh, I don't even know if you need to do something manually when running them with Valet. So it may be worthless anyway.

Thanks a lot for the suggestions!

**Comment by mattstauffer** [comment]
Great ideas and great suggestions as always @drbyte!

I don't think this would belong in the core but I'm super happy to have this conversation for others to reference if they're interested.
