### ISSUE TITLE
php_admin_value[memory_limit] determines memory limit?

### ISSUE THREAD

**Issue by chasegiunta** [laravel/valet#884]
Was trying to change php's memory_limit through the normal methods we've been using for a couple years now (`conf.d/php-memory-limits.ini` / `php.ini`) without success. I couldn't figure out why this was! phpinfo() was always reporting back 128M, regardless of what `php -i | grep memory_limit` returned. 

I had uninstalled php/valet completely, reinstalled, used different versions of php, etc.

Found this recent Stack Overflow question from someone who also got stumped by this (https://stackoverflow.com/questions/59336092/macos-laravel-valet-increase-memory-limit) and it turns out the `php_admin_value[memory_limit] = 128M` within `valet-fpm.conf` is determining the memory limit used everywhere by php?

I can see that adding the valet-fpm.conf file and those values are an intentional change introduced with 2.6.0, but unsure whether that value is supposed to be intentionally restricting the memory_limit. If so, since this is an additional config specific to valet, and not brew/php, should it be documented somewhere?

**Comment by drbyte** [comment]
You're right: that 128M can be perceived as restrictive, depending on your needs. And the addition of it in the template is over-aggressive.

PHP 7.4's defaults appear to be the following (according to what happens when all these values are commented-out in both places):

    PHP Memory Limit: 128M
    POST Max Size: 8M
    Upload Max Size: 2M

And ironically the Default FPM Pool config suggests 32M in a commented-out example.

You can address this in a couple ways:

- comment-out those `php_admin_value` entries, by adding a `;` prefix to those lines. This will cause the values from `php-memory-limits.ini` to take effect. We'll probably do this in the default Valet config.

- or edit those values directly, to suit your needs specific to FPM, separate from CLI.
