### ISSUE TITLE
php version set by valet use does not persist after reboot

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#906]
I've used valet like so `valet use php@7.4` and that makes both my php-cli and php-fpm set to 7.4.2

Everytime I reboot my Mac however (10.16.4 Mojave) I notice that the php-cli is still on 7.4 but the php-fpm reverts to php 7.3 and I have to run `valet use php@7.4` again

Anyone else getting this issue? Would appreciate some advice on how to fix it

**Comment by drbyte** [comment]
Hi @vesper8 
That sounds frustrating!

The CLI version of PHP is driven by your PATH, and when homebrew switches versions it symlinks to the correct versioned binary. So that's why it's staying on 7.4. It's a filesystem thing, working properly.

The php-fpm processes start using launchd, which homebrew also configures. While in the purest of situations homebrew will remove them properly, sometimes leftover launchAgents can be orphaned. (I supposed maybe this can happen if you've manually started php not-as-root and then come along and valet starts it as root, and then you try to switch versions and one process doesn't get cleaned up for some reason. Guessing.)

Where I'd start:
`brew services list` - what's running? Are php, nginx, dnsmasq as root?

What's the output of the following?

This will expose what versions of these are installed. Anything unexpected?
`brew list --versions | grep -E '(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s'`

Which LaunchAgents are set to run as "you"?:
`ls -al ~/Library/LaunchAgents`

... vs which ones are set to run as "root":
```sh
ls -al /Library/LaunchAgents
ls -al /Library/LaunchDaemons
```

If you run this it may tell you some warnings:
`brew services cleanup`

But even if it doesn't, I'd delete any launchAgents from your home directory that match the ones in the system launchagent or launchdaemon directories, so that there's no clash happening between them. 

Also, may be worth running the following to learn of any potential problems:
```sh
brew cleanup
brew doctor
```

(I'd also be inclined to delete all the launchAgents and launchDaemons that relate to Valet services (nginx, php, dnsmasq), then `brew install php@7.3` (because you apparently want that often) and then `valet install` to set those up again. Then reboot.)

**Comment by vesper8** [comment]
thank you @drbyte for your extremely helpful post!

These were the results of those commands

```
brew services list

dnsmasq    started root         /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd      stopped
jenkins    stopped
mysql@5.7  started omitted /Users/omitted/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx      started root         /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php        started root         /Library/LaunchDaemons/homebrew.mxcl.php.plist
php@7.2    stopped
php@7.3    error   omitted /Users/omitted/Library/LaunchAgents/homebrew.mxcl.php@7.3.plist
redis      started omitted /Users/omitted/Library/LaunchAgents/homebrew.mxcl.redis.plist
supervisor stopped
unbound    stopped
```

```
brew list --versions | grep -E '(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s'

curl-openssl 7.68.0
dnsmasq 2.80
mysql@5.7 5.7.29
nginx 1.17.3_1 1.17.8
openssl 1.0.2t
openssl@1.1 1.1.1d
php 7.4.2
php@7.2 7.2.27
php@7.3 7.3.14
```

```
ls -al ~/Library/LaunchAgents

-rw-r--r--   1 omitted  staff   957 14 Aug  2018 homebrew.mxcl.mongodb@3.6.plist
-rw-r--r--   1 omitted  staff   551 17 Nov 15:53 homebrew.mxcl.mysql@5.7.plist
-rw-r--r--   1 omitted  staff   628  1 Feb 03:12 homebrew.mxcl.php.plist
-rw-r--r--   1 omitted  staff   636  3 Dec 02:14 homebrew.mxcl.php@7.3.plist
-rw-r--r--   1 omitted  staff   823  5 May  2018 homebrew.mxcl.redis.plist
```

```
ls -al /Library/LaunchDaemons

-rw-r--r--   1 root  admin   576  6 Feb 18:38 homebrew.mxcl.dnsmasq.plist
-rw-------   1 root  wheel   587 25 May  2017 homebrew.mxcl.mariadb.plist
-rw-r--r--   1 root  admin   571 11 Feb 15:43 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628 11 Feb 15:43 homebrew.mxcl.php.plist
```

```
brew services cleanup

Warning: Service homebrew.mxcl.mongodb@3.6 not managed by `brew services` => skipping
All user-space services OK, nothing cleaned...
```

I did what you suggested, I deleted every LaunchDaemon/LaunchAgent that refered to php, nginx or dnsmasq, then ran `brew reinstall php@7.3`, then ran `valet install`

Then also ran `valet use php@7.4`

Then rebooted, and so far so good because both php-fpm and php-cli are still on 7.4

**Comment by drbyte** [comment]
Great!

Looks like this issue is resolved. As its author, you can click Close below to close it.
