### ISSUE TITLE
Installing Valet messes up /etc/hosts entries

### ISSUE THREAD

**Issue by cjstage** [laravel/valet#939]
I've been banging my head against the wall on this one.  Sometimes I use /etc/hosts before deploying some of the Wordpress sites we do to avoid downtime when switching a new site live.  I'll do entries like this:

`123.456.432.210 newwebsite.com`

After installing Valet I appears something gets messed up with this.  No longer can I make entries like this where my browsers will honor them.  I want to say it's possibly due to something that dnsmasq does?  Not too familiar with how that works under the hood so I'm hoping someone knows.

I have noticed that if I make an entry like the sample above and ping it the entry appears to work... and running dig (like browsers) _do not_ return the overridden IP.

I've confirmed this happens right after Valet is installed because I have tested this with a couple computers with fresh installs of Valet.

Is there a way to ensure /etc/hosts entries are honored while still being able to use Valet?

**Comment by drbyte** [comment]
dnsmasq's default configuration is to honor /etc/hosts as expected.
Valet doesn't change that.

In the default config it says you can uncomment a setting to tell it to *stop* using /etc/hosts:
```
# If you don't want dnsmasq to read /etc/hosts, uncomment the
# following line.
#no-hosts
# or if you want it to read another file, as well as /etc/hosts, use
# this.
#addn-hosts=/etc/banner_add_hosts
```

And, since Valet leaves that default config intact it should be operating normally.

Valet adds one thing to the dnsmasq configuration: the ability to put your own dnsmasq config files/rules into your `~/.config/valet/dnsmasq.d` directory as `*.conf` files. 
So, if you want to explore adding your own specialized rules for Dnsmasq, that's the place to do it. 
You can see the original file with all the possible configuration settings in the dnsmasq repo at:
http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=dnsmasq.conf.example

**Comment by cjstage** [comment]
I'd be interested to know, do you have any issues with records in your /etc/hosts file with valet running?  I've tested this behavior on four computers now.  The one without valet installed entries are respected instantly.  None of the ones with valet installed would honor entries post install and I've confirmed they were working before hand.

**Comment by drbyte** [comment]
I've confirmed that it works:
Added `1.1.1.1  foobar.dev` to my `/etc/hosts` 
**and restarted dnsmasq** with `valet restart dnsmasq`
then ran `dig foobar.dev` which correctly returned the following response:
`foobar.dev.		0	IN	A	1.1.1.1`

Also note that my MacOS network preferences have the only DNS server listed as 127.0.0.1 so that all queries go to dnsmasq. If you have something else listed first, move 127.0.0.1 up to the start of the list. If the list is empty, add it.

You might inspect things using:
```sh
dnsmasq --test       # this just tests for errors in the config files it reads
cat /etc/resolv.conf   # this should reflect the DNS resolvers you've entered in your MacOS system preferences
ls -al /etc/resolver      # each of these files should contain a nameserver entry pointing to 127.0.0.1
scutil --dns      # basically looking for your TLDs to be pointing to 127.0.0.1
```

Additionally, you could add the following file, to enable logging so you can inspect what dnsmasq is doing. You'll see when it restarts that the log shows that it is reading /etc/hosts and how many entries it found.

Create this file: `~/.config/valet/dnsmasq.d/logging-on.conf`
```conf
# Logging
log-facility=/Users/PUT_YOUR_USERNAME_HERE/.config/valet/Log/dnsmasq.log
log-queries
```

**Comment by cjstage** [comment]
I've confirmed that setting DNS Servers with 127.0.0.1 first, above the other nameservers does work.  I didn't have any entries in there before (default configuration network configuration).  Is this not how it should be setup by default?  I wouldn't think any of the tlds associated with valet would work if dnsmasq isn't the first to attempt resolving the domain.

**Comment by drbyte** [comment]
Yes, I usually recommend people add that entry.

Things seem to work fine without it in many cases, but adding it almost always makes things very certain to work properly.

There's an open issue exploring the pros and cons of trying to automate it, if you have anything helpful to add to the discussion: https://github.com/laravel/valet/issues/775

**Comment by cjstage** [comment]
@drbyte — defiantly, I applied that same fix to my other computers and confirmed it works there too.  I think that's defiantly the right thread to continue on.  Maybe some note about this could make its way into the documentation.  It was hard to search for, had I found that issue first I might have been able to figure it out on my own.  Thanks for the help!

**Comment by tylerwiegand** [comment]
Adding 127.0.0.1 before other options was helpful, glad this was discussed. If anyone else comes to this, you can just add it here (at least, that worked for me) 
![image](https://user-images.githubusercontent.com/11890164/89354651-3f999d80-d66e-11ea-899e-1c740ae0bb12.png)
