### ISSUE TITLE
Is the trailing slash "/" automatically added to non ".test" tlds?

### ISSUE THREAD

**Issue by TheBigK** [laravel/valet#955]
I'm currently using valet 2.10.2 and found out that if I set a non `.test` domain; my domain gets a `/` at the end of the domain. For example, if I've set `valet tld wip`; and put `myapp.wip`; Chrome quickly sets it to `myapp.wip/`. 

However, trailing slash is not added to `.test` tld. Is this a feature or a bug?

**Comment by drbyte** [comment]
This is not something Valet does on its own.
It's either your browser or your application code.

Hypothesis: In the case you mentioned of Chrome adding it, it's quite likely that since Chrome is aware that the .wip TLD is not one of the special TLDs that can be used as "local" that it is choosing to add that itself.

Aside: (Depending on browser and browser configuration, including its search-bar configuration) It's very common for one to need to actually *add* the `/` manually (if typing by hand) when first training the browser about the existence of a new domain, else the browser may interpret it as search text instead of a FQDN.

**Comment by TheBigK** [comment]
I've decided to settle with the default .test domain.
