### ISSUE TITLE
Where should I put custom nginx settings for a valet site?

### ISSUE THREAD

**Issue by mjatharvest** [laravel/valet#972]
I'm confused about where to add a custom nginx config setting for one site only using Laravel Valet.

The setting I need to change is increasing the size of the fast_cgi buffer:
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
``` 

Reading these comments:

I understand the wrong place would likely be the default nginx config files created by valet install. (Or else the settings could be lost after future update).
https://github.com/laravel/valet/issues/284#issuecomment-270225305

It sounds like the right place would be a custom valet driver or local valet driver in the site folder.
https://github.com/laravel/valet/issues/364#issuecomment-298168582

But it wasn't clear to me from the docs how to pass an nginx setting from a PHP file (the valet driver file).

Is it it possible to set nginx server settings for a site from with the local valet driver file?

**Comment by drbyte** [comment]
This is where I'd put that:
`/usr/local/etc/nginx/servers/valet_fastcgi_settings.conf`
It will affect every site, but will be less volatile since Valet (currently, although it might eventually) touch/create that file.

Alternatively you could `valet secure` a site and edit its Nginx config file as mentioned in the #284 comment you quoted. It will indeed be overwritten if you run a valet command which re-secures all sites.

**Comment by mjatharvest** [comment]
Thanks @drbyte!

Applying this setting to all sites wouldn't hurt. It's only needed on one particular site in my case.

Is it correct then that `LocalValetDriver.php` (https://laravel.com/docs/7.x/valet#local-drivers) doesn't have a way to configure nginx settings on a per site basis?

**Comment by drbyte** [comment]
> Is it correct then that `LocalValetDriver.php` (https://laravel.com/docs/7.x/valet#local-drivers) doesn't have a way to configure nginx settings on a per site basis?

Correct. You'd have to do it in the site-specific nginx config file located in `~/.config/valet/Nginx`, but as mentioned those files are usually auto-generated by various Valet commands, so are slightly volatile.

That said, an alternative to using `/usr/local/etc/nginx/servers/` is to put your custom settings at
`~/.config/valet/Nginx/valet_fastcgi_settings.conf`
... This is convenient as it's already in your own User directory and not nested down in other less-traveled areas. And, as long as you don't create a site by the same name, it will not be damaged.

**Comment by mjatharvest** [comment]
Great to know, thank you for the help!

**Comment by izshreyansh** [comment]
`/opt/homebrew/etc/nginx/valet/valet.conf`

**Comment by LTroya** [comment]
Hi @drbyte, I changed the configuration on `~/.config/valet/Nginx/mysite.io` but that is not taking effect, I always see `404 - Not found`.

I tried the following paths to set a root on the my secure Nginx site:
- `/Users/MY_USER/Code/mysite/src/web`
- `/Code/mysite/src/web` (Asuming `/` is the path as `~/.config`).
- `~/Code/mysite/src/web`

I restarted valet after every change on the nginx configuration.

None of them works. Setting a new root with `LocalValetDriver.php` is not enough because `web` is my public directory.

Is there a way to accomplish that? I will appreciate any hint

**Comment by harish-pixpa** [comment]
`cd ~/.config/valet/Nginx
`
or 

`cd ~/.valet/Nginx
`

**Comment by aubreypwd** [comment]
The reason I needed this was because I use xDebug and I needed to debug something sometimes for up to a few minutes. The only way I could get this to work was to edit the site in `~/.config/valet/Nginx/` and add `fastcgi_read_timeout 1400;` to the `location ~ [^/]\.php(/|$)` section:

<img width="1061" alt="image" src="https://github.com/laravel/valet/assets/1753298/16b1cb98-9701-4885-aad7-5aaa57dd76a0">
