### ISSUE TITLE
Serve all parked Domains as Secure by default.

### ISSUE THREAD

**Issue by bhushan** [laravel/valet#974]
Suppose i have parked all my code to `~/Code` directory ...

It has two folders `laravel-one` and `laravel-two`

now sure enough i can goto `http://laravel-one.test` and `http://laravel-two.test` by default.

but to secure domains i have to manually go into folder and serve that domain as https using `valet secure`

but i could not find any way to by default serve all parked domains as `https`

there should be way to if i create new project in `Code` directory lets say `laravel-three` so i can directly access it using `https://laravel-three.test`

**Comment by drbyte** [comment]
Given that SSL certificates work based on site-specific domain name, you have to generate a certificate for the domain.
And doing that requires also registering that certificate in Nginx so it knows to use it when serving that domain.
Further, Nginx must be restarted in order to load the new site config once it has been created/updated for the certificate. The restart introduces a brief delay.
`valet secure` does all that, and more, when you call it.

Do you have suggestions on how all that should be automated without first even telling Valet about the new directory?

**Comment by bhushan** [comment]
is it possible if i try this domain ie `http://laravel-three.test` for the first time and then it should generate all this stuffs for me.. 


I know this is resource consuming thing.. but what if i can enable disable it with `valet secure --parked=true`.

**Comment by drbyte** [comment]
Sure. Let us know how it works out.
